// Catálogo oficial DIAN del Formato 2516 · generado desde modelo110.xlsm
// NO editar manualmente · regenerar con scripts/extract_f2516_h2h3.py

export type F2516_H3Renglon = {
  id: number;        // ID estable (fila Excel)
  nivel: number;      // 1=categoría principal, 2=sub, 3=sub-sub, ...
  concepto: string;
  esSumif: boolean;   // se alimenta del balance (captura)
  esTotal: boolean;   // suma de hijos (calculado)
};

export const F2516_H3_CATALOGO: F2516_H3Renglon[] = [
  { id: 10, nivel: 1, concepto: "INGRESOS", esSumif: false, esTotal: false },
  { id: 11, nivel: 2, concepto: "Ingresos netos Actividad Industrial, comercial y servicios", esSumif: false, esTotal: false },
  { id: 12, nivel: 3, concepto: "Ingresos brutos Actividad Industrial, comercial y servicios", esSumif: false, esTotal: true },
  { id: 13, nivel: 4, concepto: "Venta de bienes", esSumif: true, esTotal: false },
  { id: 14, nivel: 6, concepto: "Exportación a otros países", esSumif: true, esTotal: false },
  { id: 15, nivel: 6, concepto: "Zona franca", esSumif: true, esTotal: false },
  { id: 16, nivel: 6, concepto: "Comercializadoras Internacionales", esSumif: true, esTotal: false },
  { id: 17, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 18, nivel: 6, concepto: "Vinculado Económicos zona Franca y exterior", esSumif: true, esTotal: false },
  { id: 19, nivel: 4, concepto: "Prestación de servicios (diferentes de honorarios profesionales)", esSumif: true, esTotal: false },
  { id: 20, nivel: 6, concepto: "Exportación a otros países", esSumif: true, esTotal: false },
  { id: 21, nivel: 6, concepto: "Zona franca", esSumif: true, esTotal: false },
  { id: 22, nivel: 6, concepto: "Comercializadoras Internacionales", esSumif: true, esTotal: false },
  { id: 23, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 24, nivel: 6, concepto: "Vinculado Económicos zona Franca y exterior", esSumif: true, esTotal: false },
  { id: 25, nivel: 4, concepto: "Servicios de construcción", esSumif: true, esTotal: false },
  { id: 26, nivel: 4, concepto: "Acuerdos de concesión de servicios", esSumif: true, esTotal: false },
  { id: 27, nivel: 4, concepto: "Arrendamientos operativos", esSumif: true, esTotal: false },
  { id: 28, nivel: 4, concepto: "Regalías", esSumif: true, esTotal: false },
  { id: 29, nivel: 4, concepto: "Comisiones (relaciones de agencia)", esSumif: true, esTotal: false },
  { id: 30, nivel: 4, concepto: "Honorarios Profesionales", esSumif: true, esTotal: false },
  { id: 31, nivel: 4, concepto: "Actividades de seguros y de capitalización", esSumif: true, esTotal: false },
  { id: 32, nivel: 4, concepto: "Liberación de reservas en contratos de seguros", esSumif: true, esTotal: false },
  { id: 33, nivel: 4, concepto: "Comisiones bancarias, costos de transacción, entre otros", esSumif: true, esTotal: false },
  { id: 34, nivel: 4, concepto: "Otros ingresos", esSumif: true, esTotal: false },
  { id: 35, nivel: 3, concepto: "Devoluciones, rebajas y descuentos", esSumif: false, esTotal: true },
  { id: 36, nivel: 4, concepto: "En venta de bienes", esSumif: true, esTotal: false },
  { id: 37, nivel: 4, concepto: "En prestación de servicios", esSumif: true, esTotal: false },
  { id: 38, nivel: 4, concepto: "Otras devoluciones, rebajas y descuentos", esSumif: true, esTotal: false },
  { id: 39, nivel: 2, concepto: "Ingresos financieros", esSumif: false, esTotal: true },
  { id: 40, nivel: 3, concepto: "Arrendamiento financiero o mercantil (leasing)", esSumif: true, esTotal: false },
  { id: 41, nivel: 3, concepto: "Intereses - sector financiero", esSumif: true, esTotal: false },
  { id: 42, nivel: 3, concepto: "Intereses por préstamos a terceros (diferentes al sector financiero)", esSumif: true, esTotal: false },
  { id: 43, nivel: 3, concepto: "Por instrumentos financieros medidos a costo amortizado distinto a préstamos", esSumif: true, esTotal: false },
  { id: 44, nivel: 3, concepto: "Intereses implícitos (transacciones de financiación)", esSumif: true, esTotal: false },
  { id: 45, nivel: 3, concepto: "Diferencia en cambio", esSumif: true, esTotal: false },
  { id: 46, nivel: 3, concepto: "Otros ingresos financieros", esSumif: true, esTotal: false },
  { id: 47, nivel: 2, concepto: "Ganancias por inversiones en subsidiarias, asociadas y/o negocios conjuntos", esSumif: false, esTotal: true },
  { id: 48, nivel: 3, concepto: "Ganancias por el método de participación", esSumif: true, esTotal: false },
  { id: 49, nivel: 3, concepto: "Ganancias cambios en el valor razonable", esSumif: true, esTotal: false },
  { id: 50, nivel: 3, concepto: "Dividendos y/o participaciones no constitutivos de renta ni ganancia ocasional (incluye capitalizaciones no gravadas)", esSumif: true, esTotal: false },
  { id: 51, nivel: 3, concepto: "Dividendos o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones.", esSumif: true, esTotal: false },
  { id: 52, nivel: 3, concepto: "Dividendos y/o participaciones gravadas a la tarifa general provenientes de sociedades y entidades extranjeras o de sociedades nacionales.", esSumif: true, esTotal: false },
  { id: 53, nivel: 3, concepto: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2016 y anteriores)", esSumif: true, esTotal: false },
  { id: 54, nivel: 3, concepto: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2017 y siguientes)", esSumif: true, esTotal: false },
  { id: 55, nivel: 3, concepto: "Dividendos y/o participaciones gravadas al 10%", esSumif: true, esTotal: false },
  { id: 56, nivel: 3, concepto: "Dividendos y/o participaciones gravadas a tarifa general (EP y sociedades extranjeras - utilidades generadas a partir del año 2017)", esSumif: true, esTotal: false },
  { id: 57, nivel: 3, concepto: "Dividendos y participaciones provenientes de proyectos calificados como mega inversión gravadas al 27%", esSumif: true, esTotal: false },
  { id: 58, nivel: 2, concepto: "Ingresos por mediciones a valor razonable", esSumif: false, esTotal: true },
  { id: 59, nivel: 3, concepto: "Activos biológicos", esSumif: true, esTotal: false },
  { id: 60, nivel: 3, concepto: "Propiedades de inversión", esSumif: true, esTotal: false },
  { id: 61, nivel: 3, concepto: "Instrumentos financieros, diferente a inversiones en subsidiarias, asociadas y/o negocios conjuntos", esSumif: true, esTotal: false },
  { id: 62, nivel: 3, concepto: "Instrumentos derivados", esSumif: true, esTotal: false },
  { id: 63, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 64, nivel: 2, concepto: "Utilidad en la venta o enajenación de activos, bienes poseídos por menos de dos años", esSumif: false, esTotal: true },
  { id: 65, nivel: 3, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 66, nivel: 3, concepto: "Propiedades de Inversión", esSumif: true, esTotal: false },
  { id: 67, nivel: 3, concepto: "Activos biológicos (sin plantas productoras)", esSumif: true, esTotal: false },
  { id: 68, nivel: 3, concepto: "Activos no corrientes mantenidos para la venta / entregar a propietarios", esSumif: true, esTotal: false },
  { id: 69, nivel: 3, concepto: "Activos Intangibles", esSumif: true, esTotal: false },
  { id: 70, nivel: 3, concepto: "Inversiones en acciones y otras participaciones", esSumif: true, esTotal: false },
  { id: 71, nivel: 3, concepto: "Por disposición de otros instrumentos financieros", esSumif: true, esTotal: false },
  { id: 72, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 73, nivel: 2, concepto: "Utilidad por venta o enajenación de activos, bienes poseídos por dos años o más (ganancia ocasional)", esSumif: false, esTotal: true },
  { id: 74, nivel: 3, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 75, nivel: 3, concepto: "Propiedades de Inversión", esSumif: true, esTotal: false },
  { id: 76, nivel: 3, concepto: "Activos biológicos (sin plantas productoras)", esSumif: true, esTotal: false },
  { id: 77, nivel: 3, concepto: "Activos no corrientes mantenidos para la venta / entregar a propietarios", esSumif: true, esTotal: false },
  { id: 78, nivel: 3, concepto: "Activos Intangibles", esSumif: true, esTotal: false },
  { id: 79, nivel: 3, concepto: "Inversiones en acciones y otras participaciones", esSumif: true, esTotal: false },
  { id: 80, nivel: 3, concepto: "Por disposición de otros instrumentos financieros", esSumif: true, esTotal: false },
  { id: 81, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 82, nivel: 2, concepto: "Ingresos por reversión de deterioro del valor", esSumif: false, esTotal: true },
  { id: 83, nivel: 3, concepto: "Inventarios", esSumif: true, esTotal: false },
  { id: 84, nivel: 3, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 85, nivel: 3, concepto: "Activos intangibles", esSumif: true, esTotal: false },
  { id: 86, nivel: 3, concepto: "Activos de exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 87, nivel: 3, concepto: "Propiedades de inversión medidas al modelo de costo", esSumif: true, esTotal: false },
  { id: 88, nivel: 3, concepto: "Activos no corrientes mantenidos para la venta / entregar a propietarios", esSumif: true, esTotal: false },
  { id: 89, nivel: 3, concepto: "Activos biológicos medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 90, nivel: 3, concepto: "Bienes de arte y cultura", esSumif: true, esTotal: false },
  { id: 91, nivel: 3, concepto: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)", esSumif: true, esTotal: false },
  { id: 92, nivel: 3, concepto: "Cartera de crédito y operaciones de leasing", esSumif: true, esTotal: false },
  { id: 93, nivel: 3, concepto: "Otras inversiones medidas al costo o el método de la participación", esSumif: true, esTotal: false },
  { id: 94, nivel: 3, concepto: "Otros deterioros", esSumif: true, esTotal: false },
  { id: 95, nivel: 2, concepto: "Ingresos por reversión de provisiones (pasivos de monto o fecha inciertos)", esSumif: false, esTotal: true },
  { id: 96, nivel: 3, concepto: "Garantías", esSumif: true, esTotal: false },
  { id: 97, nivel: 3, concepto: "Contratos onerosos", esSumif: true, esTotal: false },
  { id: 98, nivel: 3, concepto: "Litigios", esSumif: true, esTotal: false },
  { id: 99, nivel: 3, concepto: "Reembolsos a clientes", esSumif: true, esTotal: false },
  { id: 100, nivel: 3, concepto: "Reestructuraciones de negocios", esSumif: true, esTotal: false },
  { id: 101, nivel: 3, concepto: "Pasivos contingentes asumidos en una combinación de negocios", esSumif: true, esTotal: false },
  { id: 102, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 103, nivel: 2, concepto: "Ingresos por reversión de pasivos por beneficios a los empleados", esSumif: false, esTotal: true },
  { id: 104, nivel: 3, concepto: "Beneficios de corto plazo", esSumif: true, esTotal: false },
  { id: 105, nivel: 3, concepto: "Beneficios de largo plazo", esSumif: true, esTotal: false },
  { id: 106, nivel: 3, concepto: "Beneficios a empleados por terminación del vínculo laboral", esSumif: true, esTotal: false },
  { id: 107, nivel: 3, concepto: "Beneficios a empleados post-empleo", esSumif: true, esTotal: false },
  { id: 108, nivel: 2, concepto: "Otros ingresos", esSumif: false, esTotal: true },
  { id: 109, nivel: 3, concepto: "Transferencias, subvenciones y ayudas gubernamentales", esSumif: true, esTotal: false },
  { id: 110, nivel: 3, concepto: "Donaciones, aportaciones y similares", esSumif: true, esTotal: false },
  { id: 111, nivel: 3, concepto: "Reembolsos de compañías de seguros (indemnizaciones)", esSumif: true, esTotal: false },
  { id: 112, nivel: 3, concepto: "Otras indemnizaciones", esSumif: true, esTotal: false },
  { id: 113, nivel: 3, concepto: "Otras reversiones o recuperaciones", esSumif: true, esTotal: false },
  { id: 114, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 115, nivel: 2, concepto: "Ganancias netas en operaciones discontinuadas", esSumif: true, esTotal: false },
  { id: 116, nivel: 2, concepto: "Ajustes fiscales", esSumif: false, esTotal: false },
  { id: 117, nivel: 3, concepto: "Adición de ingresos", esSumif: false, esTotal: true },
  { id: 118, nivel: 4, concepto: "Recuperación de deducciones sin incidencia contable", esSumif: true, esTotal: false },
  { id: 119, nivel: 4, concepto: "Intereses presuntos", esSumif: true, esTotal: false },
  { id: 120, nivel: 4, concepto: "Mayor ingreso - Precios de Transferencia", esSumif: true, esTotal: false },
  { id: 121, nivel: 4, concepto: "Otros ingresos fiscales y no incluidos contablemente", esSumif: true, esTotal: false },
  { id: 122, nivel: 2, concepto: "Ingresos no constitutivos de renta ni ganancia ocasional", esSumif: true, esTotal: false },
  { id: 123, nivel: 2, concepto: "TOTAL INGRESOS", esSumif: false, esTotal: false },
  { id: 124, nivel: 1, concepto: "COSTOS", esSumif: false, esTotal: false },
  { id: 125, nivel: 2, concepto: "Materias primas, reventa de bienes terminados y servicios", esSumif: false, esTotal: false },
  { id: 126, nivel: 3, concepto: "Costo de ventas calculado por el sistema permanente", esSumif: true, esTotal: false },
  { id: 127, nivel: 3, concepto: "Materias primas (para procesos de producción)", esSumif: true, esTotal: false },
  { id: 128, nivel: 6, concepto: "compras locales", esSumif: true, esTotal: false },
  { id: 129, nivel: 6, concepto: "Importaciones", esSumif: true, esTotal: false },
  { id: 130, nivel: 6, concepto: "Inventario final", esSumif: true, esTotal: false },
  { id: 131, nivel: 3, concepto: "Costos de los bienes vendidos (para comerciantes por reventa de bienes terminados)", esSumif: true, esTotal: false },
  { id: 132, nivel: 6, concepto: "compras locales", esSumif: true, esTotal: false },
  { id: 133, nivel: 6, concepto: "Importaciones", esSumif: true, esTotal: false },
  { id: 134, nivel: 6, concepto: "Inventario final", esSumif: true, esTotal: false },
  { id: 135, nivel: 3, concepto: "Productos en proceso", esSumif: true, esTotal: false },
  { id: 136, nivel: 6, concepto: "Inventario final", esSumif: true, esTotal: false },
  { id: 137, nivel: 3, concepto: "Producto terminado", esSumif: true, esTotal: false },
  { id: 138, nivel: 6, concepto: "Inventario final", esSumif: true, esTotal: false },
  { id: 139, nivel: 3, concepto: "Costos en la prestación de servicios (para prestadores de servicios)", esSumif: true, esTotal: false },
  { id: 140, nivel: 3, concepto: "Otro sistema de determinación del costo de ventas", esSumif: true, esTotal: false },
  { id: 141, nivel: 3, concepto: "Ajustes", esSumif: true, esTotal: false },
  { id: 142, nivel: 2, concepto: "Mano de obra", esSumif: false, esTotal: true },
  { id: 143, nivel: 3, concepto: "Beneficios a empleados", esSumif: true, esTotal: false },
  { id: 144, nivel: 6, concepto: "De largo plazo", esSumif: true, esTotal: false },
  { id: 145, nivel: 6, concepto: "Por terminación del vínculo laboral", esSumif: true, esTotal: false },
  { id: 146, nivel: 6, concepto: "Post-empleo", esSumif: true, esTotal: false },
  { id: 147, nivel: 2, concepto: "Depreciaciones, amortizaciones y deterioros", esSumif: false, esTotal: true },
  { id: 148, nivel: 3, concepto: "Depreciación propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 149, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 150, nivel: 3, concepto: "Depreciación propiedades de inversión", esSumif: true, esTotal: false },
  { id: 151, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 152, nivel: 3, concepto: "Depreciación activos biológicos", esSumif: true, esTotal: false },
  { id: 153, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 154, nivel: 3, concepto: "Amortización activos intangibles", esSumif: true, esTotal: false },
  { id: 155, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 156, nivel: 3, concepto: "Depreciación derechos de uso en arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 157, nivel: 3, concepto: "Otras depreciaciones y amortizaciones", esSumif: true, esTotal: false },
  { id: 158, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 159, nivel: 3, concepto: "Deterioro del valor de los activos", esSumif: true, esTotal: false },
  { id: 160, nivel: 5, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 161, nivel: 5, concepto: "Activos intangibles", esSumif: true, esTotal: false },
  { id: 162, nivel: 5, concepto: "Activos de exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 163, nivel: 5, concepto: "Propiedades de inversión medidas al modelo de costo", esSumif: true, esTotal: false },
  { id: 164, nivel: 5, concepto: "Activos no corrientes mantenidos para la venta / distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 165, nivel: 5, concepto: "Activos biológicos medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 166, nivel: 5, concepto: "Bienes de arte y cultura medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 167, nivel: 5, concepto: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)", esSumif: true, esTotal: false },
  { id: 168, nivel: 5, concepto: "Cartera de crédito y operaciones de leasing", esSumif: true, esTotal: false },
  { id: 169, nivel: 5, concepto: "Otras inversiones medidas al costo o por el método de la participación", esSumif: true, esTotal: false },
  { id: 170, nivel: 5, concepto: "Derechos de uso en arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 171, nivel: 5, concepto: "Otros deterioros", esSumif: true, esTotal: false },
  { id: 172, nivel: 2, concepto: "Otros costos", esSumif: false, esTotal: true },
  { id: 173, nivel: 3, concepto: "Arrendamientos", esSumif: true, esTotal: false },
  { id: 174, nivel: 3, concepto: "Seguros", esSumif: true, esTotal: false },
  { id: 175, nivel: 3, concepto: "Servicios", esSumif: true, esTotal: false },
  { id: 176, nivel: 3, concepto: "Honorarios", esSumif: true, esTotal: false },
  { id: 177, nivel: 3, concepto: "Servicios técnicos", esSumif: true, esTotal: false },
  { id: 178, nivel: 5, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 179, nivel: 5, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 180, nivel: 3, concepto: "Asistencia técnica", esSumif: true, esTotal: false },
  { id: 181, nivel: 5, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 182, nivel: 5, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 183, nivel: 3, concepto: "Otros conceptos reconocidos como costo en el estado de resultados", esSumif: true, esTotal: false },
  { id: 184, nivel: 3, concepto: "Otros costos fiscales no reconocidos contablemente", esSumif: true, esTotal: false },
  { id: 185, nivel: 2, concepto: "Menor costo - ajuste Precios de Transferencia", esSumif: true, esTotal: false },
  { id: 186, nivel: 2, concepto: "TOTAL COSTOS", esSumif: false, esTotal: false },
  { id: 187, nivel: 1, concepto: "GASTOS", esSumif: false, esTotal: false },
  { id: 188, nivel: 2, concepto: "De administración", esSumif: false, esTotal: false },
  { id: 189, nivel: 3, concepto: "Mano de obra", esSumif: false, esTotal: true },
  { id: 190, nivel: 4, concepto: "Beneficios a empleados", esSumif: true, esTotal: false },
  { id: 191, nivel: 6, concepto: "De largo plazo", esSumif: true, esTotal: false },
  { id: 192, nivel: 6, concepto: "Por terminación del vínculo laboral", esSumif: true, esTotal: false },
  { id: 193, nivel: 6, concepto: "Post-empleo", esSumif: true, esTotal: false },
  { id: 194, nivel: 3, concepto: "Otros gastos de administración", esSumif: false, esTotal: true },
  { id: 195, nivel: 4, concepto: "Impuestos distintos al impuesto de renta y complementarios", esSumif: true, esTotal: false },
  { id: 196, nivel: 4, concepto: "Arrendamientos operativos", esSumif: true, esTotal: false },
  { id: 197, nivel: 4, concepto: "Contribuciones y afiliaciones", esSumif: true, esTotal: false },
  { id: 198, nivel: 4, concepto: "Honorarios", esSumif: true, esTotal: false },
  { id: 199, nivel: 4, concepto: "Seguros", esSumif: true, esTotal: false },
  { id: 200, nivel: 4, concepto: "Servicios administrativos", esSumif: true, esTotal: false },
  { id: 201, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 202, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 203, nivel: 4, concepto: "Regalías", esSumif: true, esTotal: false },
  { id: 204, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 205, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 206, nivel: 4, concepto: "Asistencia técnica", esSumif: true, esTotal: false },
  { id: 207, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 208, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 209, nivel: 4, concepto: "Otros servicios", esSumif: true, esTotal: false },
  { id: 210, nivel: 4, concepto: "Investigación y desarrollo", esSumif: true, esTotal: false },
  { id: 211, nivel: 4, concepto: "Gastos legales", esSumif: true, esTotal: false },
  { id: 212, nivel: 4, concepto: "Reparación, mantenimiento, adecuación e instalaciones", esSumif: true, esTotal: false },
  { id: 213, nivel: 4, concepto: "Transporte", esSumif: true, esTotal: false },
  { id: 214, nivel: 4, concepto: "Otros gastos", esSumif: true, esTotal: false },
  { id: 215, nivel: 3, concepto: "Depreciaciones, amortizaciones y deterioros", esSumif: false, esTotal: true },
  { id: 216, nivel: 4, concepto: "Depreciación propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 217, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 218, nivel: 4, concepto: "Depreciación propiedades de inversión", esSumif: true, esTotal: false },
  { id: 219, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 220, nivel: 4, concepto: "Depreciación Arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 221, nivel: 4, concepto: "Otras depreciaciones", esSumif: true, esTotal: false },
  { id: 222, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 223, nivel: 4, concepto: "Amortización activos intangibles", esSumif: true, esTotal: false },
  { id: 224, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 225, nivel: 4, concepto: "Otras amortizaciones", esSumif: true, esTotal: false },
  { id: 226, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 227, nivel: 4, concepto: "Deterioro del valor de los activos", esSumif: true, esTotal: false },
  { id: 228, nivel: 5, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 229, nivel: 5, concepto: "Activos intangibles", esSumif: true, esTotal: false },
  { id: 230, nivel: 5, concepto: "Activos de exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 231, nivel: 5, concepto: "Propiedades de inversión medidas al modelo de costo", esSumif: true, esTotal: false },
  { id: 232, nivel: 5, concepto: "Activos no corrientes mantenidos para la venta / distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 233, nivel: 5, concepto: "Bienes de arte y cultura medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 234, nivel: 5, concepto: "Activos biológicos medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 235, nivel: 5, concepto: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)", esSumif: true, esTotal: false },
  { id: 236, nivel: 5, concepto: "Cartera de crédito y operaciones de leasing", esSumif: true, esTotal: false },
  { id: 237, nivel: 5, concepto: "Otras inversiones medidas al costo o por el método de la participación", esSumif: true, esTotal: false },
  { id: 238, nivel: 5, concepto: "Derechos de uso en arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 239, nivel: 5, concepto: "Otros deterioros", esSumif: true, esTotal: false },
  { id: 240, nivel: 2, concepto: "Gastos de distribución y ventas", esSumif: false, esTotal: false },
  { id: 241, nivel: 3, concepto: "Mano de obra", esSumif: false, esTotal: true },
  { id: 242, nivel: 4, concepto: "Beneficios a empleados", esSumif: true, esTotal: false },
  { id: 243, nivel: 6, concepto: "De largo plazo", esSumif: true, esTotal: false },
  { id: 244, nivel: 6, concepto: "Por terminación del vínculo laboral", esSumif: true, esTotal: false },
  { id: 245, nivel: 6, concepto: "Post-empleo", esSumif: true, esTotal: false },
  { id: 246, nivel: 3, concepto: "Otros gastos de distribución y ventas", esSumif: false, esTotal: true },
  { id: 247, nivel: 4, concepto: "Impuestos distintos al impuesto de renta y complementarios", esSumif: true, esTotal: false },
  { id: 248, nivel: 4, concepto: "Arrendamientos operativos", esSumif: true, esTotal: false },
  { id: 249, nivel: 4, concepto: "Contribuciones y afiliaciones", esSumif: true, esTotal: false },
  { id: 250, nivel: 4, concepto: "Honorarios", esSumif: true, esTotal: false },
  { id: 251, nivel: 4, concepto: "Seguros", esSumif: true, esTotal: false },
  { id: 252, nivel: 4, concepto: "Servicios administrativos", esSumif: true, esTotal: false },
  { id: 253, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 254, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 255, nivel: 4, concepto: "Regalías", esSumif: true, esTotal: false },
  { id: 256, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 257, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 258, nivel: 4, concepto: "Asistencia técnica", esSumif: true, esTotal: false },
  { id: 259, nivel: 6, concepto: "Jurisdicciones no cooperantes, de baja o nula imposición y regímenes tributarios preferenciales", esSumif: true, esTotal: false },
  { id: 260, nivel: 6, concepto: "No vinculados", esSumif: true, esTotal: false },
  { id: 261, nivel: 4, concepto: "Otros servicios", esSumif: true, esTotal: false },
  { id: 262, nivel: 4, concepto: "Investigación y desarrollo", esSumif: true, esTotal: false },
  { id: 263, nivel: 4, concepto: "Gastos legales", esSumif: true, esTotal: false },
  { id: 264, nivel: 4, concepto: "Reparación, mantenimiento, adecuación e instalaciones", esSumif: true, esTotal: false },
  { id: 265, nivel: 4, concepto: "Transporte", esSumif: true, esTotal: false },
  { id: 266, nivel: 4, concepto: "Constitución de reservas (empresas aseguradoras)", esSumif: true, esTotal: false },
  { id: 267, nivel: 4, concepto: "Liquidación de siniestros", esSumif: true, esTotal: false },
  { id: 268, nivel: 4, concepto: "Primas de reaseguros", esSumif: true, esTotal: false },
  { id: 269, nivel: 4, concepto: "Otros gastos", esSumif: true, esTotal: false },
  { id: 270, nivel: 3, concepto: "Depreciaciones, amortizaciones y deterioros", esSumif: false, esTotal: true },
  { id: 271, nivel: 4, concepto: "Depreciación propiedades, planta y equipo", esSumif: true, esTotal: true },
  { id: 272, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 273, nivel: 4, concepto: "Depreciación propiedades de inversión", esSumif: true, esTotal: false },
  { id: 274, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 275, nivel: 4, concepto: "Depreciación activos biológicos", esSumif: true, esTotal: false },
  { id: 276, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 277, nivel: 4, concepto: "Amortización activos intangibles", esSumif: true, esTotal: false },
  { id: 278, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 279, nivel: 4, concepto: "Depreciación Arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 280, nivel: 4, concepto: "Otras depreciaciones y amortizaciones", esSumif: true, esTotal: false },
  { id: 281, nivel: 6, concepto: "Del ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: true },
  { id: 282, nivel: 4, concepto: "Deterioro del valor de los activos", esSumif: true, esTotal: false },
  { id: 283, nivel: 5, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: true },
  { id: 284, nivel: 5, concepto: "Activos intangibles", esSumif: true, esTotal: false },
  { id: 285, nivel: 5, concepto: "Activos de exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 286, nivel: 5, concepto: "Propiedades de inversión medidas al modelo de costo", esSumif: true, esTotal: false },
  { id: 287, nivel: 5, concepto: "Activos no corrientes mantenidos para la venta o para distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 288, nivel: 5, concepto: "Bienes de arte y cultura medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 289, nivel: 5, concepto: "Activos biológicos medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 290, nivel: 5, concepto: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)", esSumif: true, esTotal: false },
  { id: 291, nivel: 5, concepto: "Cartera de crédito y operaciones de leasing", esSumif: true, esTotal: false },
  { id: 292, nivel: 5, concepto: "Otras inversiones medidas al costo o el método de la participación", esSumif: true, esTotal: false },
  { id: 293, nivel: 5, concepto: "Derechos de uso en arrendamientos operativos (NIIF 16)", esSumif: true, esTotal: false },
  { id: 294, nivel: 5, concepto: "Otros deterioros", esSumif: true, esTotal: false },
  { id: 295, nivel: 2, concepto: "Gastos financieros", esSumif: false, esTotal: true },
  { id: 296, nivel: 3, concepto: "Arrendamiento", esSumif: true, esTotal: false },
  { id: 297, nivel: 6, concepto: "Operativo (NIIF 16)", esSumif: true, esTotal: false },
  { id: 298, nivel: 3, concepto: "Intereses  devengados - sector financiero", esSumif: true, esTotal: false },
  { id: 299, nivel: 3, concepto: "Intereses devengados por préstamos de terceros (distinto al sector financiero)", esSumif: true, esTotal: false },
  { id: 300, nivel: 3, concepto: "Por instrumentos financieros medidos a costo amortizado distinto a préstamos", esSumif: true, esTotal: false },
  { id: 301, nivel: 3, concepto: "Costos de transacción", esSumif: true, esTotal: false },
  { id: 302, nivel: 3, concepto: "Diferencia en cambio", esSumif: true, esTotal: false },
  { id: 303, nivel: 3, concepto: "Intereses implícitos (transacciones de financiación)", esSumif: true, esTotal: false },
  { id: 304, nivel: 3, concepto: "Actualización de provisiones reconocidas a valor presente", esSumif: true, esTotal: false },
  { id: 305, nivel: 3, concepto: "Intereses por acciones preferenciales", esSumif: true, esTotal: false },
  { id: 306, nivel: 3, concepto: "Otros gastos financieros reconocidos como gasto en el estado de resultados", esSumif: true, esTotal: false },
  { id: 307, nivel: 2, concepto: "Pérdidas por inversiones en subsidiarias, asociadas y/o negocios conjuntos", esSumif: false, esTotal: true },
  { id: 308, nivel: 3, concepto: "Pérdidas por el método de participación", esSumif: true, esTotal: false },
  { id: 309, nivel: 3, concepto: "Pérdidas por mediciones a valor razonable", esSumif: true, esTotal: false },
  { id: 310, nivel: 2, concepto: "Pérdidas por mediciones a valor razonable", esSumif: false, esTotal: true },
  { id: 311, nivel: 3, concepto: "Activos biológicos", esSumif: true, esTotal: false },
  { id: 312, nivel: 3, concepto: "Propiedades de inversión", esSumif: true, esTotal: false },
  { id: 313, nivel: 3, concepto: "Instrumentos financieros", esSumif: true, esTotal: false },
  { id: 314, nivel: 3, concepto: "Instrumentos derivados", esSumif: true, esTotal: false },
  { id: 315, nivel: 3, concepto: "Otras", esSumif: true, esTotal: false },
  { id: 316, nivel: 2, concepto: "Pérdida en la venta o enajenación de activos fijos", esSumif: false, esTotal: true },
  { id: 317, nivel: 3, concepto: "Propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 318, nivel: 3, concepto: "propiedades de inversión", esSumif: true, esTotal: false },
  { id: 319, nivel: 3, concepto: "Activos no corrientes mantenidos para la venta / entregar a propietarios", esSumif: true, esTotal: false },
  { id: 320, nivel: 3, concepto: "Valoración y venta de inversiones fondo de liquidez y títulos participativos, entre otros", esSumif: true, esTotal: false },
  { id: 321, nivel: 3, concepto: "Por disposición de otros instrumentos financieros", esSumif: true, esTotal: false },
  { id: 322, nivel: 3, concepto: "Activos Intangibles", esSumif: true, esTotal: false },
  { id: 323, nivel: 3, concepto: "Descuento en operaciones de factoring", esSumif: true, esTotal: false },
  { id: 324, nivel: 3, concepto: "Inversiones en acciones y otras participaciones", esSumif: true, esTotal: false },
  { id: 325, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 326, nivel: 2, concepto: "Gastos por provisiones (pasivos de monto o fecha inciertos)", esSumif: false, esTotal: true },
  { id: 327, nivel: 3, concepto: "Garantías", esSumif: true, esTotal: false },
  { id: 328, nivel: 3, concepto: "Contratos onerosos", esSumif: true, esTotal: false },
  { id: 329, nivel: 3, concepto: "Litigios", esSumif: true, esTotal: false },
  { id: 330, nivel: 3, concepto: "Reembolsos a clientes", esSumif: true, esTotal: false },
  { id: 331, nivel: 3, concepto: "Reestructuraciones de negocios", esSumif: true, esTotal: false },
  { id: 332, nivel: 3, concepto: "Pasivos contingentes asumidos en una combinación de negocios", esSumif: true, esTotal: false },
  { id: 333, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 334, nivel: 2, concepto: "Otros gastos", esSumif: false, esTotal: true },
  { id: 335, nivel: 3, concepto: "Transferencias, subvenciones y ayudas gubernamentales", esSumif: true, esTotal: false },
  { id: 336, nivel: 3, concepto: "Donaciones, aportaciones y similares", esSumif: true, esTotal: false },
  { id: 337, nivel: 3, concepto: "Contribuciones a educación de los empleados", esSumif: true, esTotal: false },
  { id: 338, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 339, nivel: 3, concepto: "Deducciones fiscales no reconocidos contablemente", esSumif: true, esTotal: false },
  { id: 340, nivel: 2, concepto: "Pérdidas netas en operaciones discontinuadas", esSumif: true, esTotal: false },
  { id: 341, nivel: 2, concepto: "Menor gasto o deducción -  Ajuste Precios de Transferencia", esSumif: true, esTotal: false },
  { id: 342, nivel: 2, concepto: "TOTAL GASTOS", esSumif: false, esTotal: false },
  { id: 343, nivel: 1, concepto: "GANANCIA O PÉRDIDA ANTES DE IMPUESTO A LA RENTA (incluyendo dividendos)", esSumif: false, esTotal: false },
  { id: 344, nivel: 1, concepto: "CLASIFICACIÓN DE DIFERENCIAS", esSumif: false, esTotal: false },
  { id: 345, nivel: 1, concepto: "AJUSTES AL RESULTADO CONTABLE POR DIFERENCIAS PERMANENTES", esSumif: false, esTotal: false },
  { id: 347, nivel: 2, concepto: "Diferencias permanentes que disminuyen la Renta Líquida (-)", esSumif: false, esTotal: true },
  { id: 348, nivel: 3, concepto: "Ingresos no constitutivos de renta ni ganancia ocasional", esSumif: false, esTotal: false },
  { id: 349, nivel: 3, concepto: "Utilidad en la venta o enajenación de activos poseídos por dos años o más (ganancia ocasional)", esSumif: false, esTotal: false },
  { id: 350, nivel: 3, concepto: "Ganancias por el método de participación", esSumif: false, esTotal: false },
  { id: 351, nivel: 3, concepto: "Otros beneficios fiscales", esSumif: false, esTotal: false },
  { id: 352, nivel: 5, concepto: "Inversiones en investigación, desarrollo tecnológico e innovación", esSumif: false, esTotal: false },
  { id: 353, nivel: 5, concepto: "Mayor valor del costo de los activos fijos por reajustes fiscales o saneamientos año 1995", esSumif: false, esTotal: false },
  { id: 354, nivel: 5, concepto: "Recuperación de deducciones (valor fiscal)", esSumif: false, esTotal: false },
  { id: 355, nivel: 5, concepto: "Salarios con deducciones especiales", esSumif: false, esTotal: false },
  { id: 356, nivel: 5, concepto: "Reintegro o recuperación de provisiones que constituyan diferencias permanentes, en períodos anteriores – provisiones para gastos no deducibles", esSumif: false, esTotal: false },
  { id: 357, nivel: 5, concepto: "Ajuste por atribución de rentas establecimientos permanentes y sucursales", esSumif: false, esTotal: false },
  { id: 358, nivel: 5, concepto: "Otros beneficios fiscales de naturaleza permanente", esSumif: false, esTotal: false },
  { id: 359, nivel: 2, concepto: "Diferencias permanentes que aumentan la Renta Líquida (+)", esSumif: false, esTotal: true },
  { id: 360, nivel: 3, concepto: "Pérdidas y Gastos no deducibles", esSumif: false, esTotal: false },
  { id: 361, nivel: 5, concepto: "Gastos sin soporte", esSumif: false, esTotal: false },
  { id: 362, nivel: 5, concepto: "Pagos al exterior sin la prueba de la retención en la fuente", esSumif: false, esTotal: false },
  { id: 363, nivel: 5, concepto: "Pagos al exterior que exceden el 15% de la renta líquida", esSumif: false, esTotal: false },
  { id: 364, nivel: 5, concepto: "Donaciones que no cumplan los requisitos legales", esSumif: false, esTotal: false },
  { id: 365, nivel: 5, concepto: "Salarios sin el pago de los aportes parafiscales", esSumif: false, esTotal: false },
  { id: 366, nivel: 5, concepto: "Gastos de vigencias anteriores", esSumif: false, esTotal: false },
  { id: 367, nivel: 5, concepto: "Gasto financiero no deducible por regla de subcapitalización", esSumif: false, esTotal: false },
  { id: 368, nivel: 5, concepto: "Otros gastos financieros no deducibles", esSumif: false, esTotal: false },
  { id: 369, nivel: 5, concepto: "Deterioro de inversiones para cubrir una pérdida en enajenación de acciones", esSumif: false, esTotal: false },
  { id: 370, nivel: 5, concepto: "Pérdida en la enajenación de acciones y venta de bienes inmuebles", esSumif: false, esTotal: false },
  { id: 371, nivel: 5, concepto: "Pérdidas no deducibles por faltantes de inventarios", esSumif: false, esTotal: false },
  { id: 372, nivel: 5, concepto: "Perdidas por el método de participación", esSumif: false, esTotal: false },
  { id: 373, nivel: 5, concepto: "Pagos de regalías por concepto de intangibles a vinculados del exterior y zonas francas", esSumif: false, esTotal: false },
  { id: 374, nivel: 5, concepto: "Limitación de costos por compras a proveedores ficticios o insolventes", esSumif: false, esTotal: false },
  { id: 375, nivel: 5, concepto: "Impuestos, multas, sanciones, intereses moratorios y las condenas no deducibles", esSumif: false, esTotal: false },
  { id: 376, nivel: 5, concepto: "Gastos que no guardan relación de causalidad y necesidad con la actividad productora de renta", esSumif: false, esTotal: false },
  { id: 377, nivel: 5, concepto: "Monto que supera el límite permitido para atenciones a clientes, proveedores y empleados", esSumif: false, esTotal: false },
  { id: 378, nivel: 5, concepto: "Importación de tecnología, patentes y marcas", esSumif: false, esTotal: false },
  { id: 379, nivel: 5, concepto: "Gastos no deducibles en contratos de arrendamientos, de naturaleza permanente", esSumif: false, esTotal: false },
  { id: 380, nivel: 5, concepto: "Gastos no deducibles por operaciones gravadas con IVA realizadas con personas no inscritas como responsables del Impuesto Sobre las Ventas", esSumif: false, esTotal: false },
  { id: 381, nivel: 5, concepto: "Gasto no deducible por donaciones", esSumif: false, esTotal: false },
  { id: 382, nivel: 5, concepto: "Gastos no deducibles, atribuibles a ingresos exentos o no constitutivos de renta ni ganancia ocasional", esSumif: false, esTotal: false },
  { id: 383, nivel: 5, concepto: "Otros gastos no deducibles de naturaleza permanente", esSumif: false, esTotal: false },
  { id: 384, nivel: 3, concepto: "Otros Ajustes", esSumif: false, esTotal: false },
  { id: 385, nivel: 5, concepto: "Rentas liquidas por ventas de inversiones", esSumif: false, esTotal: false },
  { id: 386, nivel: 5, concepto: "Mayor ingreso, ajustes por precios de transferencia", esSumif: false, esTotal: false },
  { id: 387, nivel: 5, concepto: "Menor costo o deducción, ajustes por precios de transferencia", esSumif: false, esTotal: false },
  { id: 388, nivel: 5, concepto: "Rentas líquidas por recuperación de deducciones de naturaleza permanente", esSumif: false, esTotal: false },
  { id: 389, nivel: 5, concepto: "Ajuste por atribución de rentas establecimientos permanentes y sucursales", esSumif: false, esTotal: false },
  { id: 390, nivel: 5, concepto: "Otros ajustes", esSumif: false, esTotal: false },
  { id: 391, nivel: 2, concepto: "GANANCIA O PÉRDIDA CONTABLE CON DIFERENCIAS PERMANENTES", esSumif: false, esTotal: false },
  { id: 392, nivel: 1, concepto: "AJUSTES AL RESULTADO CONTABLE POR DIFERENCIAS TEMPORALES (que afectan el resultado)", esSumif: false, esTotal: false },
  { id: 393, nivel: 2, concepto: "Diferencias temporales deducibles", esSumif: false, esTotal: false },
  { id: 394, nivel: 3, concepto: "Pérdidas por deterioro del valor de los activos", esSumif: true, esTotal: false },
  { id: 395, nivel: 5, concepto: "Propiedades, planta y equipo,", esSumif: true, esTotal: false },
  { id: 396, nivel: 5, concepto: "Activos intangibles", esSumif: true, esTotal: false },
  { id: 397, nivel: 5, concepto: "Activos de exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 398, nivel: 5, concepto: "Propiedades de inversión medidas al modelo de costo", esSumif: true, esTotal: false },
  { id: 399, nivel: 5, concepto: "Activos no corrientes mantenidos para la venta / distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 400, nivel: 5, concepto: "Activos biológicos medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 401, nivel: 5, concepto: "Bienes de arte y cultura medidos al modelo de costo", esSumif: true, esTotal: false },
  { id: 402, nivel: 5, concepto: "Activos financieros (diferentes a cartera de crédito y operaciones de leasing)", esSumif: true, esTotal: false },
  { id: 403, nivel: 5, concepto: "Cartera de crédito y operaciones de leasing", esSumif: true, esTotal: false },
  { id: 404, nivel: 5, concepto: "Otras inversiones medidas al costo o por el método de la participación", esSumif: true, esTotal: false },
  { id: 405, nivel: 5, concepto: "Otras pérdidas por deterioro", esSumif: true, esTotal: false },
  { id: 406, nivel: 3, concepto: "Gastos por Depreciación que han excedido el límite máximo fiscal", esSumif: true, esTotal: false },
  { id: 407, nivel: 6, concepto: "Propiedades de inversión", esSumif: true, esTotal: false },
  { id: 408, nivel: 6, concepto: "Activos biológicos", esSumif: true, esTotal: false },
  { id: 409, nivel: 6, concepto: "Bienes de arte y cultura", esSumif: true, esTotal: false },
  { id: 410, nivel: 6, concepto: "Otros activos", esSumif: true, esTotal: false },
  { id: 411, nivel: 3, concepto: "Gastos por amortización que han excedido el límite máximo fiscal", esSumif: true, esTotal: false },
  { id: 412, nivel: 3, concepto: "Pérdidas por medición a Valor Razonable", esSumif: true, esTotal: false },
  { id: 413, nivel: 6, concepto: "Instrumentos derivados", esSumif: true, esTotal: false },
  { id: 414, nivel: 6, concepto: "Otros instrumentos financieros, diferentes a títulos de renta fija, medidos al modelo del valor razonable", esSumif: true, esTotal: false },
  { id: 415, nivel: 3, concepto: "Pérdida por diferencia en cambio", esSumif: true, esTotal: false },
  { id: 416, nivel: 3, concepto: "Pérdidas esperadas en contratos de construcción y otros servicios (provisiones por contratos onerosos)", esSumif: true, esTotal: false },
  { id: 417, nivel: 3, concepto: "Intereses implícitos (ventas o préstamos concedidos a terceros)", esSumif: true, esTotal: false },
  { id: 418, nivel: 3, concepto: "Otras Provisiones asociadas a pasivos de monto o fecha inciertos", esSumif: true, esTotal: false },
  { id: 419, nivel: 3, concepto: "Por beneficios a empleados", esSumif: true, esTotal: false },
  { id: 420, nivel: 3, concepto: "Gastos por actualización de provisiones reconocidas a valor presente", esSumif: true, esTotal: false },
  { id: 421, nivel: 3, concepto: "Costos por préstamos atribuibles a activos aptos para entidades que aplican la NIIF para PYMES", esSumif: true, esTotal: false },
  { id: 422, nivel: 3, concepto: "Pasivos por ingresos diferidos producto de programas de fidelización de clientes que no han sido reversados contablemente pero que deben ser gravados fiscalmente", esSumif: true, esTotal: false },
  { id: 423, nivel: 3, concepto: "Ajustes por contratos de concesión que incorporan las etapas de construcción, administración, operación y mantenimiento", esSumif: true, esTotal: false },
  { id: 424, nivel: 3, concepto: "Gastos de establecimiento", esSumif: true, esTotal: false },
  { id: 425, nivel: 3, concepto: "Gastos de investigación, desarrollo e innovación", esSumif: true, esTotal: false },
  { id: 426, nivel: 3, concepto: "Por pagos basados en acciones", esSumif: true, esTotal: false },
  { id: 427, nivel: 3, concepto: "En la explotación de minas, petróleo y gas", esSumif: true, esTotal: false },
  { id: 428, nivel: 3, concepto: "Rentas con derecho a cobro (causadas) que no cumplieron criterios para ser contabilizadas como ingresos del período gravable", esSumif: true, esTotal: false },
  { id: 429, nivel: 3, concepto: "Otras diferencias temporales deducibles", esSumif: true, esTotal: false },
  { id: 430, nivel: 3, concepto: "Total diferencias temporales deducibles", esSumif: false, esTotal: true },
  { id: 431, nivel: 2, concepto: "Diferencias temporales imponibles (gravables)", esSumif: false, esTotal: false },
  { id: 432, nivel: 3, concepto: "Gastos por depreciaciones de activos fijos no aceptadas fiscalmente de naturaleza temporaria", esSumif: true, esTotal: false },
  { id: 433, nivel: 6, concepto: "Aplicación del modelo de revaluación", esSumif: true, esTotal: false },
  { id: 434, nivel: 6, concepto: "Costos estimados de desmantelamiento", esSumif: true, esTotal: false },
  { id: 435, nivel: 6, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 436, nivel: 3, concepto: "Gastos por amortizaciones de activos intangibles no aceptadas fiscalmente de naturaleza temporaria", esSumif: true, esTotal: false },
  { id: 437, nivel: 6, concepto: "Aplicación del modelo de revaluación", esSumif: true, esTotal: false },
  { id: 438, nivel: 6, concepto: "Plusvalía (Good Will, fondo de comercio y crédito mercantil)", esSumif: true, esTotal: false },
  { id: 439, nivel: 6, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 440, nivel: 3, concepto: "Ganancias por la medición a valor razonable", esSumif: true, esTotal: false },
  { id: 441, nivel: 6, concepto: "Instrumentos derivados", esSumif: true, esTotal: false },
  { id: 442, nivel: 6, concepto: "Otros instrumentos financieros, diferentes a títulos de renta fija medidos al valor razonable", esSumif: true, esTotal: false },
  { id: 443, nivel: 3, concepto: "Ganancia por diferencia en cambio", esSumif: true, esTotal: false },
  { id: 444, nivel: 3, concepto: "Ingresos provenientes por contraprestación variable", esSumif: true, esTotal: false },
  { id: 445, nivel: 3, concepto: "Intereses implícitos (compras o préstamos obtenidos)", esSumif: true, esTotal: false },
  { id: 446, nivel: 3, concepto: "Deducción especial del impuesto sobre las ventas", esSumif: true, esTotal: false },
  { id: 447, nivel: 3, concepto: "Otras diferencias temporales imponibles (gravables)", esSumif: true, esTotal: false },
  { id: 448, nivel: 3, concepto: "Total diferencias temporales imponibles", esSumif: false, esTotal: true },
  { id: 449, nivel: 2, concepto: "Otras diferencias temporales", esSumif: false, esTotal: false },
  { id: 451, nivel: 3, concepto: "Mediciones de activos biológicos al valor razonable menos costos de venta", esSumif: true, esTotal: false },
  { id: 452, nivel: 6, concepto: "Costos de producción atribuibles a la transformación biológica ó pérdidas causadas en caso de destrucción, daños, muerte y otros eventos", esSumif: true, esTotal: false },
  { id: 453, nivel: 6, concepto: "Depreciación fiscal de animales productores", esSumif: true, esTotal: false },
  { id: 454, nivel: 3, concepto: "Ajustes por títulos de renta fija (activos financieros) medidos al modelo del valor razonable", esSumif: true, esTotal: false },
  { id: 455, nivel: 6, concepto: "Ajuste por rendimientos financieros calculados de manera lineal para efectos fiscales", esSumif: true, esTotal: false },
  { id: 456, nivel: 3, concepto: "Gastos por amortización fiscal acelerada", esSumif: true, esTotal: false },
  { id: 457, nivel: 3, concepto: "Ajustes por operaciones de reporto o repo, simultáneas y de transferencia temporal de valores", esSumif: true, esTotal: false },
  { id: 458, nivel: 3, concepto: "Contratos de arrendamientos", esSumif: true, esTotal: false },
  { id: 459, nivel: 3, concepto: "Total otras diferencias temporales", esSumif: false, esTotal: true },
  { id: 460, nivel: 1, concepto: "RENTA LÍQUIDA ORDINARIA DEL EJERCICIO", esSumif: false, esTotal: false },
  { id: 461, nivel: 1, concepto: "PÉRDIDA LÍQUIDA DEL EJERCICIO", esSumif: false, esTotal: false },
  { id: 462, nivel: 1, concepto: "AJUSTES PARA LIQUIDACION", esSumif: false, esTotal: false },
  { id: 463, nivel: 1, concepto: "ESAL (R.T.E.)", esSumif: true, esTotal: false },
  { id: 464, nivel: 4, concepto: "Valor Inversiones liquidadas en el período", esSumif: true, esTotal: false },
  { id: 465, nivel: 1, concepto: "Renta Pasiva - ECE sin residencia fiscal en Colombia", esSumif: false, esTotal: false },
  { id: 466, nivel: 2, concepto: "Ingresos", esSumif: true, esTotal: false },
  { id: 467, nivel: 4, concepto: "Intereses y rendimientos financieros", esSumif: true, esTotal: false },
  { id: 468, nivel: 4, concepto: "Provenientes de activos intangibles", esSumif: true, esTotal: false },
  { id: 469, nivel: 4, concepto: "Enajenación o cesión de derechos", esSumif: true, esTotal: false },
  { id: 470, nivel: 4, concepto: "Enajenación o arrendamiento de inmuebles", esSumif: true, esTotal: false },
  { id: 471, nivel: 4, concepto: "Compra o venta de bienes corporales", esSumif: true, esTotal: false },
  { id: 472, nivel: 4, concepto: "Por servicios", esSumif: true, esTotal: false },
  { id: 473, nivel: 4, concepto: "TOTAL", esSumif: false, esTotal: true },
  { id: 474, nivel: 2, concepto: "Costos", esSumif: true, esTotal: false },
  { id: 475, nivel: 2, concepto: "Deducciones", esSumif: true, esTotal: false },
  { id: 476, nivel: 2, concepto: "RENTA LIQUIDA PASIVA", esSumif: false, esTotal: false },
  { id: 477, nivel: 1, concepto: "RENTA LÍQUIDA POR RECUPERACIÓN DE DEDUCCIONES", esSumif: true, esTotal: false },
  { id: 478, nivel: 1, concepto: "RENTA LIQUIDA ORDINARIA DEL EJERCICIO - EXCEDENTE NETO", esSumif: false, esTotal: false },
  { id: 479, nivel: 1, concepto: "PERDIDA LIQUIDA DEL EJERCICIO", esSumif: false, esTotal: false },
  { id: 480, nivel: 1, concepto: "Compensaciones", esSumif: false, esTotal: true },
  { id: 481, nivel: 2, concepto: "De pérdidas fiscales", esSumif: false, esTotal: false },
  { id: 482, nivel: 2, concepto: "Del exceso de renta presuntiva sobre renta ordinaria", esSumif: false, esTotal: false },
  { id: 483, nivel: 1, concepto: "Renta líquida", esSumif: false, esTotal: false },
  { id: 484, nivel: 1, concepto: "Renta presuntiva período gravable", esSumif: false, esTotal: false },
  { id: 485, nivel: 2, concepto: "Patrimonio líquido del año o período gravable anterior", esSumif: false, esTotal: false },
  { id: 486, nivel: 2, concepto: "Valor patrimonial neto", esSumif: false, esTotal: false },
  { id: 487, nivel: 5, concepto: "Bienes afectados por hechos constitutivos de fuerza mayor o caso fortuito", esSumif: false, esTotal: false },
  { id: 488, nivel: 5, concepto: "Bienes vinculados a empresas en período improductivo", esSumif: false, esTotal: false },
  { id: 489, nivel: 5, concepto: "Bienes destinados exclusivamente a actividades deportivas", esSumif: false, esTotal: false },
  { id: 490, nivel: 5, concepto: "Bienes vinculados a empresas exclusivamente mineras", esSumif: false, esTotal: false },
  { id: 491, nivel: 2, concepto: "Primeras 19.000 UVT de activos destinados al sector agropecuario", esSumif: false, esTotal: false },
  { id: 492, nivel: 2, concepto: "Otras exclusiones", esSumif: false, esTotal: false },
  { id: 493, nivel: 2, concepto: "Base de cálculo de la renta presuntiva", esSumif: false, esTotal: false },
  { id: 494, nivel: 2, concepto: "Cálculo renta presuntiva (0,0%)", esSumif: false, esTotal: false },
  { id: 495, nivel: 2, concepto: "Renta gravable generada por los activos excluidos", esSumif: false, esTotal: false },
  { id: 496, nivel: 1, concepto: "Renta Exenta", esSumif: false, esTotal: false },
  { id: 497, nivel: 1, concepto: "Rentas gravables (renta líquida)", esSumif: false, esTotal: true },
  { id: 498, nivel: 2, concepto: "Otras rentas gravables", esSumif: true, esTotal: false },
  { id: 499, nivel: 2, concepto: "Pasivos inexistentes", esSumif: true, esTotal: false },
  { id: 500, nivel: 2, concepto: "Omisión de activos", esSumif: true, esTotal: false },
  { id: 501, nivel: 2, concepto: "Comparación patrimonial", esSumif: true, esTotal: false },
  { id: 502, nivel: 2, concepto: "ESAL (R.T.E.)", esSumif: true, esTotal: false },
  { id: 503, nivel: 5, concepto: "Asignaciones permanentes no ejecutadas", esSumif: true, esTotal: false },
  { id: 504, nivel: 5, concepto: "Inversiones liquidadas y no reinvertidas", esSumif: true, esTotal: false },
  { id: 505, nivel: 1, concepto: "Rentas líquidas gravables nacionales a tarifa general)", esSumif: false, esTotal: false },
  { id: 506, nivel: 1, concepto: "Impuesto sobre la renta líquida gravable", esSumif: false, esTotal: false },
  { id: 507, nivel: 1, concepto: "Ganancias Ocasionales gravables", esSumif: false, esTotal: false },
  { id: 508, nivel: 2, concepto: "Ingresos por ganancia ocasional en venta de activos fijos", esSumif: false, esTotal: false },
  { id: 509, nivel: 2, concepto: "Otros ingresos por ganancia ocasional", esSumif: false, esTotal: false },
  { id: 510, nivel: 2, concepto: "Total Ingresos por ganancias ocasionales", esSumif: false, esTotal: true },
  { id: 511, nivel: 2, concepto: "Costos por ganancia ocasional en venta de activos fijos", esSumif: false, esTotal: false },
  { id: 512, nivel: 2, concepto: "Otros costos por ganancias ocasionales", esSumif: false, esTotal: false },
  { id: 513, nivel: 2, concepto: "Total costos por ganancias ocasionales", esSumif: false, esTotal: true },
  { id: 514, nivel: 2, concepto: "Ganancias ocasionales no gravadas por la venta de acciones ECE", esSumif: false, esTotal: false },
  { id: 515, nivel: 2, concepto: "Otras ganancias ocasionales no gravadas y exentas", esSumif: false, esTotal: false },
  { id: 516, nivel: 2, concepto: "Rentas deudores régimen Ley 1116 de 2006, Decretos 560 y 772 de 2020", esSumif: false, esTotal: false },
  { id: 517, nivel: 2, concepto: "Utilización pérdidas fiscales acumuladas (Inc. 2, Art 15 Decreto 772 de 2020)", esSumif: false, esTotal: false },
  { id: 518, nivel: 2, concepto: "Impuesto de ganancia ocasional", esSumif: false, esTotal: false },
  { id: 519, nivel: 1, concepto: "Descuentos tributarios", esSumif: false, esTotal: false },
  { id: 520, nivel: 1, concepto: "Descuento por impuestos pagados en el exterior por ganancias ocasionales", esSumif: false, esTotal: false },
  { id: 521, nivel: 1, concepto: "Valor inversión Obras por Impuestos hasta del 50 % del valor del impuesto a cargo (modalidad de pago 1)", esSumif: false, esTotal: false },
  { id: 522, nivel: 1, concepto: "Descuento efectivo inversión obras por impuestos (modalidad de pago 2)", esSumif: false, esTotal: false },
  { id: 523, nivel: 1, concepto: "Anticipo renta liquidado año anterior", esSumif: false, esTotal: false },
  { id: 525, nivel: 1, concepto: "Anticipo sobretasa liquidado año gravable anterior", esSumif: false, esTotal: false },
  { id: 526, nivel: 1, concepto: "Saldo a favor año gravable anterior sin solicitud de devolución o compensación", esSumif: false, esTotal: false },
  { id: 527, nivel: 1, concepto: "Autorretenciones", esSumif: true, esTotal: false },
  { id: 528, nivel: 5, concepto: "Por servicios", esSumif: true, esTotal: false },
  { id: 529, nivel: 5, concepto: "Por rendimientos financieros", esSumif: true, esTotal: false },
  { id: 530, nivel: 5, concepto: "Autorretención Decreto 2201 del 2016", esSumif: true, esTotal: false },
  { id: 531, nivel: 5, concepto: "Total autorretenciones", esSumif: false, esTotal: true },
  { id: 532, nivel: 1, concepto: "Otras retenciones", esSumif: true, esTotal: false },
  { id: 533, nivel: 5, concepto: "Por servicios.", esSumif: true, esTotal: false },
  { id: 534, nivel: 5, concepto: "Por honorarios y comisiones", esSumif: true, esTotal: false },
  { id: 535, nivel: 5, concepto: "Por rendimientos financieros.", esSumif: true, esTotal: false },
  { id: 536, nivel: 5, concepto: "Por dividendos y participaciones", esSumif: true, esTotal: false },
  { id: 537, nivel: 5, concepto: "Otras retenciones", esSumif: true, esTotal: false },
  { id: 538, nivel: 5, concepto: "Total otras retenciones", esSumif: false, esTotal: true },
  { id: 539, nivel: 1, concepto: "Total retenciones año gravable que declara", esSumif: false, esTotal: false },
  { id: 540, nivel: 1, concepto: "Anticipo renta por el año gravable siguiente", esSumif: false, esTotal: false },
  { id: 541, nivel: 1, concepto: "Anticipo Puntos adicionales año gravable anterior", esSumif: false, esTotal: false },
  { id: 542, nivel: 1, concepto: "Puntos adicionales a la tarifa del impuesto renta", esSumif: false, esTotal: false },
  { id: 543, nivel: 1, concepto: "Anticipo Puntos adicionales año gravable siguiente", esSumif: false, esTotal: false },
  { id: 544, nivel: 1, concepto: "Crédito fiscal para inversiones en proyectos de investigación, desarrollo tecnológico e innovación o vinculación de capital humano de alto nivel", esSumif: false, esTotal: false },
  { id: 545, nivel: 1, concepto: "Sanciones", esSumif: false, esTotal: false },
  { id: 546, nivel: 1, concepto: "Valor a Adicionar por ajuste a la tasa mínima de tributación", esSumif: false, esTotal: false },
  { id: 547, nivel: 1, concepto: "Impuesto a Adicionar, límite a beneficios y estímulos tributarios", esSumif: false, esTotal: false },
  { id: 548, nivel: 1, concepto: "OTRO RESULTADO INTEGRAL (ORI)", esSumif: false, esTotal: false },
  { id: 550, nivel: 2, concepto: "No se reclasifican al resultado", esSumif: false, esTotal: false },
  { id: 551, nivel: 4, concepto: "Nuevas mediciones de los planes de beneficios definidos", esSumif: false, esTotal: false },
  { id: 552, nivel: 4, concepto: "Inversiones en instrumentos de patrimonio", esSumif: false, esTotal: false },
  { id: 553, nivel: 4, concepto: "Participación otro resultado integral de asociadas y negocios conjuntos contabilizados utilizando el método de la participación", esSumif: false, esTotal: false },
  { id: 554, nivel: 4, concepto: "Instrumentos de cobertura que cubren inversiones en instrumentos de patrimonio", esSumif: false, esTotal: false },
  { id: 555, nivel: 4, concepto: "Cambio valor razonable de pasivos financieros atribuible a cambios en el riesgo de crédito del pasivo", esSumif: false, esTotal: false },
  { id: 556, nivel: 2, concepto: "Se reclasifican al resultado", esSumif: false, esTotal: false },
  { id: 557, nivel: 4, concepto: "Activos financieros disponibles para la venta", esSumif: false, esTotal: false },
  { id: 558, nivel: 4, concepto: "Activos financieros medidos al valor razonable con cambios en el ORI", esSumif: false, esTotal: false },
  { id: 559, nivel: 4, concepto: "Cobertura de flujos de efectivo", esSumif: false, esTotal: false },
  { id: 560, nivel: 4, concepto: "Coberturas de inversiones netas en negocios en el extranjero", esSumif: false, esTotal: false },
  { id: 561, nivel: 4, concepto: "Otras partidas que deban ser reconocidas en el ORI", esSumif: false, esTotal: false },
  { id: 562, nivel: 2, concepto: "OTRO RESULTADO INTEGRAL ANTES DE IMPUESTOS", esSumif: false, esTotal: true },
  { id: 563, nivel: 1, concepto: "RESULTADO INTEGRAL TOTAL DEL AÑO", esSumif: false, esTotal: false },
  { id: 564, nivel: 1, concepto: "Gasto / ingreso impuesto de renta y complementario del período", esSumif: false, esTotal: false },
  { id: 565, nivel: 2, concepto: "Impuesto corriente", esSumif: false, esTotal: false },
  { id: 566, nivel: 5, concepto: "Gastos por ajustes respecto a períodos anteriores", esSumif: false, esTotal: false },
  { id: 567, nivel: 5, concepto: "Ingreso por ajustes respecto a períodos anteriores", esSumif: false, esTotal: false },
  { id: 568, nivel: 5, concepto: "Impuestos asumidos del exterior - convenios o tratados", esSumif: false, esTotal: false },
  { id: 569, nivel: 2, concepto: "Gasto por impuesto diferido", esSumif: false, esTotal: false },
  { id: 570, nivel: 2, concepto: "Ingreso impuesto diferido", esSumif: false, esTotal: false },
  { id: 571, nivel: 2, concepto: "Valor neto gasto por impuesto", esSumif: false, esTotal: false },
  { id: 572, nivel: 1, concepto: "DATOS INFORMATIVOS", esSumif: false, esTotal: false },
  { id: 573, nivel: 2, concepto: "INGRESOS", esSumif: false, esTotal: false },
  { id: 574, nivel: 4, concepto: "Ingresos fiscales por fidelización de clientes, sin devengo contable", esSumif: false, esTotal: false },
  { id: 575, nivel: 4, concepto: "Retiros para consumo y publicidad, propaganda y promoción", esSumif: false, esTotal: false },
  { id: 576, nivel: 4, concepto: "Dividendos decretados en el periodo gravable", esSumif: false, esTotal: false },
  { id: 577, nivel: 4, concepto: "Dividendos cobrados en el periodo gravable", esSumif: false, esTotal: false },
  { id: 578, nivel: 4, concepto: "Ingresos devengados de fideicomisos o encargos fiduciarios, calidad de fideicomitente o fiduciante", esSumif: false, esTotal: false },
  { id: 579, nivel: 4, concepto: "Ingresos devengados de fideicomisos o encargos fiduciarios, calidad de beneficiario", esSumif: false, esTotal: false },
  { id: 580, nivel: 2, concepto: "COSTOS Y GASTOS", esSumif: false, esTotal: false },
  { id: 581, nivel: 4, concepto: "Bajas de inventarios (faltantes, caso fortuito o fuerza mayor), reconocidos como costo o gasto en el estado de resultados del ejercicio", esSumif: false, esTotal: false },
  { id: 582, nivel: 4, concepto: "Costos indirectos de producción no distribuidos como costo del inventario, reconocidos como costo o gasto en el estado de resultados del ejercicio", esSumif: false, esTotal: false },
  { id: 583, nivel: 4, concepto: "Monto descuentos obtenidos en el período en la compra de inventarios", esSumif: false, esTotal: false },
  { id: 584, nivel: 4, concepto: "Costos y gastos devengados de fideicomisos o encargos fiduciarios, calidad de fideicomitente o fiduciante", esSumif: false, esTotal: false },
  { id: 585, nivel: 4, concepto: "Costos y gastos devengados de fideicomisos o encargos fiduciarios, calidad de beneficiario", esSumif: false, esTotal: false },
  { id: 586, nivel: 4, concepto: "Costos y deducciones no procedentes - Actividad meritoria (Régimen Tributario Especial)", esSumif: false, esTotal: false },
  { id: 587, nivel: 2, concepto: "OTROS DATOS INFORMATIVOS", esSumif: false, esTotal: false },
  { id: 588, nivel: 4, concepto: "Aportes al sistema de seguridad social", esSumif: false, esTotal: false },
  { id: 589, nivel: 4, concepto: "Aportes al SENA, ICBF, cajas de compensación", esSumif: false, esTotal: false },
  { id: 590, nivel: 4, concepto: "Aportes del empleador a los seguros privados de pensiones y a los fondos de pensiones voluntarias", esSumif: false, esTotal: false },
  { id: 591, nivel: 4, concepto: "Operaciones con vinculados económicos", esSumif: false, esTotal: false },
  { id: 592, nivel: 6, concepto: "Costos y deducciones", esSumif: false, esTotal: false },
  { id: 593, nivel: 6, concepto: "Compra de inventarios", esSumif: false, esTotal: false },
  { id: 594, nivel: 6, concepto: "compra de activos fijos", esSumif: false, esTotal: false },
  { id: 595, nivel: 6, concepto: "Pasivo", esSumif: false, esTotal: false },
  { id: 596, nivel: 4, concepto: "Bases para calcular el límite a beneficios y estímulos tributarios", esSumif: false, esTotal: false },
  { id: 597, nivel: 6, concepto: "Descuento para inversiones realizadas en control, conservación y mejoramiento del medio ambiente, Art. 255 del E.T.", esSumif: false, esTotal: false },
  { id: 598, nivel: 6, concepto: "Becas por impuestos, Art. 257-1 del E.T.", esSumif: false, esTotal: false },
  { id: 599, nivel: 6, concepto: "Financiación de los estudios de los trabajadores en instituciones de educación superior, Art. 124 de la Ley 30 de 1992", esSumif: false, esTotal: false },
  { id: 600, nivel: 6, concepto: "Estímulos al patrimonio cultural de la nación, Art. 56 de la Ley 397 de 1997", esSumif: false, esTotal: false },
  { id: 601, nivel: 6, concepto: "Estímulos para el proceso de capitalización, Art. 44 de la Ley 789 de 2002", esSumif: false, esTotal: false },
  { id: 602, nivel: 6, concepto: "Deducción por ocupación de trabajadoras mujeres víctimas de la violencia comprobada, Art. 23 de la ley 1257 de 2008", esSumif: false, esTotal: false },
  { id: 603, nivel: 6, concepto: "Deducción por inversiones, Art. 4 de la Ley 1493 de 2011", esSumif: false, esTotal: false },
];
