// Catálogo del Detalle Fiscal · estructura completa del Formato 2516
// extraída del archivo guía v5 (Tribai_R110_AG2025_v5_prueba_aries.xlsx
// hoja "Detalle Fiscal").
//
// Cada renglón del F110 (R33 a R114) tiene asociadas las cuentas PUC
// que lo componen en el balance contable. La estructura permite
// generar el F2516 oficial DIAN agregando los saldos del balance por
// prefijo PUC y mostrando la conciliación contable → fiscal.
//
// NO EDITAR A MANO. Regenerar con:
//   python3 scripts/build_f2516_detalle_ts.py

export type DetalleFiscalItem = {
  /** Renglón F110 al que agrega esta cuenta (null para subtotales). */
  rgl: number | null;
  /** Código PUC. null para filas de total/sección. */
  puc: string | null;
  /** Concepto descriptivo. */
  concepto: string;
  /** "renglon_total" | "cuenta" */
  tipo: "renglon_total" | "cuenta";
};

export const DETALLE_FISCAL_2516: readonly DetalleFiscalItem[] = [
  { rgl: 33, puc: null, concepto: "Costos y gastos de nomina", tipo: "renglon_total" },
  { rgl: null, puc: "5105", concepto: "Sueldos y salarios", tipo: "cuenta" },
  { rgl: null, puc: "5110", concepto: "Horas extras y recargos", tipo: "cuenta" },
  { rgl: null, puc: "5115", concepto: "Comisiones", tipo: "cuenta" },
  { rgl: null, puc: "5120", concepto: "Viaticos", tipo: "cuenta" },
  { rgl: null, puc: "5125", concepto: "Auxilio de transporte", tipo: "cuenta" },
  { rgl: null, puc: "5130", concepto: "Cesantias", tipo: "cuenta" },
  { rgl: null, puc: "5135", concepto: "Intereses sobre cesantias", tipo: "cuenta" },
  { rgl: null, puc: "5140", concepto: "Prima de servicios", tipo: "cuenta" },
  { rgl: null, puc: "5145", concepto: "Vacaciones", tipo: "cuenta" },
  { rgl: null, puc: "5150", concepto: "Dotacion y suministros", tipo: "cuenta" },
  { rgl: null, puc: "5155", concepto: "Bonificaciones", tipo: "cuenta" },
  { rgl: null, puc: "5195", concepto: "Otros gastos de personal", tipo: "cuenta" },
  { rgl: 34, puc: null, concepto: "Aportes al sistema de seguridad social", tipo: "renglon_total" },
  { rgl: null, puc: "5160", concepto: "Aportes a EPS", tipo: "cuenta" },
  { rgl: null, puc: "5165", concepto: "Aportes a ARL", tipo: "cuenta" },
  { rgl: null, puc: "5170", concepto: "Aportes a pensiones", tipo: "cuenta" },
  { rgl: null, puc: "5175", concepto: "Aportes a cajas de compensacion", tipo: "cuenta" },
  { rgl: 35, puc: null, concepto: "Aportes parafiscales", tipo: "renglon_total" },
  { rgl: null, puc: "5180", concepto: "Aportes ICBF", tipo: "cuenta" },
  { rgl: null, puc: "5185", concepto: "Aportes SENA", tipo: "cuenta" },
  { rgl: 36, puc: null, concepto: "Efectivo y equivalentes de efectivo", tipo: "renglon_total" },
  { rgl: null, puc: "1105", concepto: "Caja", tipo: "cuenta" },
  { rgl: null, puc: "1110", concepto: "Bancos", tipo: "cuenta" },
  { rgl: null, puc: "1130", concepto: "Efectivo restringido", tipo: "cuenta" },
  { rgl: null, puc: "1120", concepto: "Fondos", tipo: "cuenta" },
  { rgl: null, puc: "1140", concepto: "Inversiones a la vista", tipo: "cuenta" },
  { rgl: 37, puc: null, concepto: "Inversiones e instrumentos financieros derivados", tipo: "renglon_total" },
  { rgl: null, puc: "1205", concepto: "Acciones", tipo: "cuenta" },
  { rgl: null, puc: "1210", concepto: "Cuotas o partes de interes social", tipo: "cuenta" },
  { rgl: null, puc: "1215", concepto: "Bonos", tipo: "cuenta" },
  { rgl: null, puc: "1220", concepto: "Cedulas", tipo: "cuenta" },
  { rgl: null, puc: "1225", concepto: "Certificados", tipo: "cuenta" },
  { rgl: null, puc: "1230", concepto: "Papeles comerciales", tipo: "cuenta" },
  { rgl: null, puc: "1235", concepto: "Titulos", tipo: "cuenta" },
  { rgl: null, puc: "1240", concepto: "Aceptaciones bancarias", tipo: "cuenta" },
  { rgl: null, puc: "1245", concepto: "Derechos fiduciarios", tipo: "cuenta" },
  { rgl: null, puc: "1250", concepto: "Derechos de recompra", tipo: "cuenta" },
  { rgl: null, puc: "1255", concepto: "Obligatorias", tipo: "cuenta" },
  { rgl: null, puc: "1260", concepto: "Cuentas en participacion", tipo: "cuenta" },
  { rgl: 38, puc: null, concepto: "Cuentas, documentos y arrendamientos por cobrar", tipo: "renglon_total" },
  { rgl: null, puc: "1305", concepto: "Clientes", tipo: "cuenta" },
  { rgl: null, puc: "1310", concepto: "Cuentas corrientes comerciales", tipo: "cuenta" },
  { rgl: null, puc: "1315", concepto: "Cuentas por cobrar a socios", tipo: "cuenta" },
  { rgl: null, puc: "1320", concepto: "Cuentas por cobrar a vinculados", tipo: "cuenta" },
  { rgl: null, puc: "1325", concepto: "Cuentas por cobrar a directores", tipo: "cuenta" },
  { rgl: null, puc: "1330", concepto: "Anticipos y avances", tipo: "cuenta" },
  { rgl: null, puc: "1335", concepto: "Depositos", tipo: "cuenta" },
  { rgl: null, puc: "1340", concepto: "Promesas de compraventa", tipo: "cuenta" },
  { rgl: null, puc: "1345", concepto: "Ingresos por cobrar", tipo: "cuenta" },
  { rgl: null, puc: "1350", concepto: "Retencion sobre contratos", tipo: "cuenta" },
  { rgl: null, puc: "1355", concepto: "Anticipo de impuestos", tipo: "cuenta" },
  { rgl: null, puc: "1360", concepto: "Cuentas por cobrar trabajadores", tipo: "cuenta" },
  { rgl: null, puc: "1365", concepto: "Prestamos a particulares", tipo: "cuenta" },
  { rgl: null, puc: "1380", concepto: "Deudores varios", tipo: "cuenta" },
  { rgl: null, puc: "1390", concepto: "Deudas de dificil cobro", tipo: "cuenta" },
  { rgl: null, puc: "1399", concepto: "Provision de cartera (-)", tipo: "cuenta" },
  { rgl: 39, puc: null, concepto: "Inventarios", tipo: "renglon_total" },
  { rgl: null, puc: "1405", concepto: "Materias primas", tipo: "cuenta" },
  { rgl: null, puc: "1410", concepto: "Productos en proceso", tipo: "cuenta" },
  { rgl: null, puc: "1415", concepto: "Productos terminados", tipo: "cuenta" },
  { rgl: null, puc: "1420", concepto: "Mercancias no fabricadas por la empresa", tipo: "cuenta" },
  { rgl: null, puc: "1425", concepto: "Materiales, repuestos y accesorios", tipo: "cuenta" },
  { rgl: null, puc: "1430", concepto: "Envases y empaques", tipo: "cuenta" },
  { rgl: null, puc: "1435", concepto: "Inventarios en transito", tipo: "cuenta" },
  { rgl: null, puc: "1499", concepto: "Provision de inventarios (-)", tipo: "cuenta" },
  { rgl: 40, puc: null, concepto: "Activos intangibles", tipo: "renglon_total" },
  { rgl: null, puc: "1605", concepto: "Credito mercantil (goodwill)", tipo: "cuenta" },
  { rgl: null, puc: "1610", concepto: "Marcas", tipo: "cuenta" },
  { rgl: null, puc: "1615", concepto: "Patentes", tipo: "cuenta" },
  { rgl: null, puc: "1620", concepto: "Concesiones y franquicias", tipo: "cuenta" },
  { rgl: null, puc: "1625", concepto: "Derechos", tipo: "cuenta" },
  { rgl: null, puc: "1630", concepto: "Know how", tipo: "cuenta" },
  { rgl: null, puc: "1635", concepto: "Licencias", tipo: "cuenta" },
  { rgl: null, puc: "1698", concepto: "Amortizacion acumulada (-)", tipo: "cuenta" },
  { rgl: 41, puc: null, concepto: "Activos biologicos", tipo: "renglon_total" },
  { rgl: null, puc: "(BIO1)", concepto: "Activos biológicos - ingrese cuenta PUC (1)", tipo: "cuenta" },
  { rgl: null, puc: "(BIO2)", concepto: "Activos biológicos - ingrese cuenta PUC (2)", tipo: "cuenta" },
  { rgl: null, puc: "(BIO3)", concepto: "Activos biológicos - ingrese cuenta PUC (3)", tipo: "cuenta" },
  { rgl: 42, puc: null, concepto: "Propiedades, planta y equipo, propiedades de inversion", tipo: "renglon_total" },
  { rgl: null, puc: "1504", concepto: "Terrenos", tipo: "cuenta" },
  { rgl: null, puc: "1506", concepto: "Materiales proyectos petroleros", tipo: "cuenta" },
  { rgl: null, puc: "1512", concepto: "Maquinaria en montaje", tipo: "cuenta" },
  { rgl: null, puc: "1520", concepto: "Maquinaria y equipo", tipo: "cuenta" },
  { rgl: null, puc: "1524", concepto: "Equipo de oficina", tipo: "cuenta" },
  { rgl: null, puc: "1528", concepto: "Equipo de computacion", tipo: "cuenta" },
  { rgl: null, puc: "1532", concepto: "Equipo medico-cientifico", tipo: "cuenta" },
  { rgl: null, puc: "1536", concepto: "Equipo de hoteles y restaurantes", tipo: "cuenta" },
  { rgl: null, puc: "1540", concepto: "Flota y equipo de transporte", tipo: "cuenta" },
  { rgl: null, puc: "1544", concepto: "Flota y equipo fluvial", tipo: "cuenta" },
  { rgl: null, puc: "1548", concepto: "Flota y equipo aereo", tipo: "cuenta" },
  { rgl: null, puc: "1552", concepto: "Flota y equipo ferreo", tipo: "cuenta" },
  { rgl: null, puc: "1556", concepto: "Acueductos, plantas y redes", tipo: "cuenta" },
  { rgl: null, puc: "1560", concepto: "Armamento de vigilancia", tipo: "cuenta" },
  { rgl: null, puc: "1562", concepto: "Envases y empaques", tipo: "cuenta" },
  { rgl: null, puc: "1564", concepto: "Plantaciones agricolas", tipo: "cuenta" },
  { rgl: null, puc: "1568", concepto: "Vias de comunicacion", tipo: "cuenta" },
  { rgl: null, puc: "1572", concepto: "Minas y canteras", tipo: "cuenta" },
  { rgl: null, puc: "1576", concepto: "Pozos artesianos", tipo: "cuenta" },
  { rgl: null, puc: "1580", concepto: "Yacimientos", tipo: "cuenta" },
  { rgl: null, puc: "1584", concepto: "Semovientes", tipo: "cuenta" },
  { rgl: null, puc: "1588", concepto: "Propiedades de inversion", tipo: "cuenta" },
  { rgl: null, puc: "1592", concepto: "Depreciacion acumulada (-)", tipo: "cuenta" },
  { rgl: null, puc: "1596", concepto: "Depreciacion diferida", tipo: "cuenta" },
  { rgl: null, puc: "1597", concepto: "Amortizacion acumulada (-)", tipo: "cuenta" },
  { rgl: null, puc: "1598", concepto: "Agotamiento acumulado (-)", tipo: "cuenta" },
  { rgl: null, puc: "1599", concepto: "Provisiones (-)", tipo: "cuenta" },
  { rgl: 43, puc: null, concepto: "Otros activos", tipo: "renglon_total" },
  { rgl: null, puc: "1705", concepto: "Gastos pagados por anticipado", tipo: "cuenta" },
  { rgl: null, puc: "1710", concepto: "Cargos diferidos", tipo: "cuenta" },
  { rgl: null, puc: "1715", concepto: "Activos por impuesto diferido", tipo: "cuenta" },
  { rgl: null, puc: "1720", concepto: "Bienes de arte y cultura", tipo: "cuenta" },
  { rgl: null, puc: "1798", concepto: "Otros activos no clasificados", tipo: "cuenta" },
  { rgl: 45, puc: null, concepto: "Total pasivos", tipo: "renglon_total" },
  { rgl: null, puc: "2105", concepto: "Obligaciones financieras", tipo: "cuenta" },
  { rgl: null, puc: "2205", concepto: "Proveedores nacionales", tipo: "cuenta" },
  { rgl: null, puc: "2210", concepto: "Proveedores del exterior", tipo: "cuenta" },
  { rgl: null, puc: "2305", concepto: "Cuentas por pagar - Cuentas corrientes", tipo: "cuenta" },
  { rgl: null, puc: "2310", concepto: "Cuentas por pagar a socios", tipo: "cuenta" },
  { rgl: null, puc: "2315", concepto: "Cuentas por pagar a vinculados", tipo: "cuenta" },
  { rgl: null, puc: "2320", concepto: "Cuentas por pagar a contratistas", tipo: "cuenta" },
  { rgl: null, puc: "2335", concepto: "Costos y gastos por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2101", concepto: "Obligaciones financieras (2101 alterno)", tipo: "cuenta" },
  { rgl: null, puc: "2345", concepto: "Acreedores oficiales", tipo: "cuenta" },
  { rgl: null, puc: "2355", concepto: "Deudas con accionistas", tipo: "cuenta" },
  { rgl: null, puc: "2360", concepto: "Dividendos por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2365", concepto: "Retencion en la fuente por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2367", concepto: "Impuesto a las ventas retenido", tipo: "cuenta" },
  { rgl: null, puc: "2368", concepto: "Impuesto de industria y comercio retenido", tipo: "cuenta" },
  { rgl: null, puc: "2370", concepto: "Retenciones y aportes de nomina", tipo: "cuenta" },
  { rgl: null, puc: "2380", concepto: "Acreedores varios", tipo: "cuenta" },
  { rgl: null, puc: "2404", concepto: "Impuesto de renta por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2408", concepto: "IVA por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2412", concepto: "ICA por pagar", tipo: "cuenta" },
  { rgl: null, puc: "2424", concepto: "Gravamen a los movimientos financieros", tipo: "cuenta" },
  { rgl: null, puc: "2505", concepto: "Obligaciones laborales", tipo: "cuenta" },
  { rgl: null, puc: "2510", concepto: "Cesantias consolidadas", tipo: "cuenta" },
  { rgl: null, puc: "2515", concepto: "Intereses sobre cesantias", tipo: "cuenta" },
  { rgl: null, puc: "2520", concepto: "Prima de servicios", tipo: "cuenta" },
  { rgl: null, puc: "2525", concepto: "Vacaciones consolidadas", tipo: "cuenta" },
  { rgl: null, puc: "2530", concepto: "Prestaciones extralegales", tipo: "cuenta" },
  { rgl: null, puc: "2605", concepto: "Pasivos estimados - Para costos y gastos", tipo: "cuenta" },
  { rgl: null, puc: "2610", concepto: "Para obligaciones laborales", tipo: "cuenta" },
  { rgl: null, puc: "2615", concepto: "Para obligaciones fiscales", tipo: "cuenta" },
  { rgl: null, puc: "2550", concepto: "Beneficios a empleados largo plazo", tipo: "cuenta" },
  { rgl: null, puc: "2705", concepto: "Ingresos recibidos por anticipado", tipo: "cuenta" },
  { rgl: null, puc: "2805", concepto: "Otros pasivos - Anticipos y avances recibidos", tipo: "cuenta" },
  { rgl: null, puc: "2815", concepto: "Ingresos recibidos para terceros", tipo: "cuenta" },
  { rgl: null, puc: "2895", concepto: "Otros pasivos diversos", tipo: "cuenta" },
  { rgl: null, puc: "2905", concepto: "Pasivo por impuesto diferido", tipo: "cuenta" },
  { rgl: 47, puc: null, concepto: "Ingresos brutos de actividades ordinarias", tipo: "renglon_total" },
  { rgl: null, puc: "4105", concepto: "Agricultura, ganaderia, caza, silvicultura", tipo: "cuenta" },
  { rgl: null, puc: "4110", concepto: "Pesca", tipo: "cuenta" },
  { rgl: null, puc: "4115", concepto: "Explotacion de minas y canteras", tipo: "cuenta" },
  { rgl: null, puc: "4120", concepto: "Industrias manufactureras", tipo: "cuenta" },
  { rgl: null, puc: "4125", concepto: "Suministro de electricidad, gas y vapor", tipo: "cuenta" },
  { rgl: null, puc: "4130", concepto: "Construccion", tipo: "cuenta" },
  { rgl: null, puc: "4135", concepto: "Comercio al por mayor y menor", tipo: "cuenta" },
  { rgl: null, puc: "4140", concepto: "Hoteles y restaurantes", tipo: "cuenta" },
  { rgl: null, puc: "4145", concepto: "Transporte, almacenamiento y comunicaciones", tipo: "cuenta" },
  { rgl: null, puc: "4150", concepto: "Actividad financiera", tipo: "cuenta" },
  { rgl: null, puc: "4155", concepto: "Actividades inmobiliarias", tipo: "cuenta" },
  { rgl: null, puc: "4160", concepto: "Servicios sociales y de salud", tipo: "cuenta" },
  { rgl: null, puc: "4165", concepto: "Servicios de ensenanza", tipo: "cuenta" },
  { rgl: null, puc: "4170", concepto: "Servicios de consultoria", tipo: "cuenta" },
  { rgl: null, puc: "(ver R59)", concepto: "Devoluciones reclasificadas a R59", tipo: "cuenta" },
  { rgl: null, puc: "4180", concepto: "Ingresos diversos (cuenta 4180)", tipo: "cuenta" },
  { rgl: 48, puc: null, concepto: "Ingresos brutos por rendimientos financieros", tipo: "renglon_total" },
  { rgl: null, puc: "4205", concepto: "Intereses", tipo: "cuenta" },
  { rgl: null, puc: "4210", concepto: "Rendimientos de inversiones", tipo: "cuenta" },
  { rgl: null, puc: "4215", concepto: "Descuentos comerciales condicionados", tipo: "cuenta" },
  { rgl: null, puc: "4220", concepto: "Utilidad en venta de inversiones", tipo: "cuenta" },
  { rgl: null, puc: "4225", concepto: "Diferencia en cambio", tipo: "cuenta" },
  { rgl: 49, puc: null, concepto: "Dividendos y/o participaciones 2016 y anteriores (no gravados)", tipo: "renglon_total" },
  { rgl: 50, puc: null, concepto: "Dividendos y/o participaciones 2017-2018 (no gravados art 49 ET)", tipo: "renglon_total" },
  { rgl: 51, puc: null, concepto: "Dividendos 2017-2018 gravados art 49 par 2", tipo: "renglon_total" },
  { rgl: 52, puc: null, concepto: "Dividendos 2019-2022 no gravados (art 49 numeral 3)", tipo: "renglon_total" },
  { rgl: 53, puc: null, concepto: "Dividendos 2019-2022 gravados", tipo: "renglon_total" },
  { rgl: 54, puc: null, concepto: "Dividendos 2023+ no gravados (art 49 num 3)", tipo: "renglon_total" },
  { rgl: 55, puc: null, concepto: "Dividendos 2023+ gravados", tipo: "renglon_total" },
  { rgl: 56, puc: null, concepto: "Dividendos recibidos de ECE", tipo: "renglon_total" },
  { rgl: 57, puc: null, concepto: "Otros ingresos", tipo: "renglon_total" },
  { rgl: null, puc: "4240", concepto: "Recuperaciones", tipo: "cuenta" },
  { rgl: null, puc: "4245", concepto: "Indemnizaciones", tipo: "cuenta" },
  { rgl: null, puc: "4250", concepto: "Participacion en concordatos", tipo: "cuenta" },
  { rgl: null, puc: "4255", concepto: "Ingresos de ejercicios anteriores", tipo: "cuenta" },
  { rgl: null, puc: "4295", concepto: "Ingresos diversos", tipo: "cuenta" },
  { rgl: 58, puc: null, concepto: "TOTAL INGRESOS BRUTOS (suma R47 a R57)", tipo: "renglon_total" },
  { rgl: 59, puc: null, concepto: "Devoluciones, rebajas y descuentos en ventas", tipo: "renglon_total" },
  { rgl: 60, puc: null, concepto: "Ingresos no constitutivos de renta (INCRNGO)", tipo: "renglon_total" },
  { rgl: 61, puc: null, concepto: "Total ingresos netos (R58 - R59 - R60)", tipo: "renglon_total" },
  { rgl: 62, puc: null, concepto: "Costos", tipo: "renglon_total" },
  { rgl: null, puc: "6105", concepto: "Costo de ventas - Comercio", tipo: "cuenta" },
  { rgl: null, puc: "6110", concepto: "Costo de ventas - Industria", tipo: "cuenta" },
  { rgl: null, puc: "6115", concepto: "Costo de ventas - Servicios", tipo: "cuenta" },
  { rgl: null, puc: "6120", concepto: "Costo de produccion", tipo: "cuenta" },
  { rgl: null, puc: "6125", concepto: "Costo de mano de obra", tipo: "cuenta" },
  { rgl: null, puc: "6130", concepto: "Costo materiales", tipo: "cuenta" },
  { rgl: null, puc: "6135", concepto: "CIF - Costos indirectos de fabricacion", tipo: "cuenta" },
  { rgl: null, puc: "7", concepto: "Costos de produccion/operacion (clase 7)", tipo: "cuenta" },
  { rgl: 63, puc: null, concepto: "Gastos de administracion", tipo: "renglon_total" },
  { rgl: 64, puc: null, concepto: "Gastos de comercializacion y ventas", tipo: "renglon_total" },
  { rgl: 65, puc: null, concepto: "Gastos financieros - Intereses y demas gastos", tipo: "renglon_total" },
  { rgl: 66, puc: null, concepto: "Otros gastos y deducciones", tipo: "renglon_total" },
  { rgl: 67, puc: null, concepto: "Total costos y gastos deducibles (R62+R63+R64+R65+R66)", tipo: "renglon_total" },
  { rgl: 68, puc: null, concepto: "Inversiones efectuadas en el año", tipo: "renglon_total" },
  { rgl: 72, puc: null, concepto: "Renta líquida ordinaria del ejercicio (R61 + R69 + R70 + R71 - R67 - R68 - dividendos R49..R56)", tipo: "renglon_total" },
  { rgl: 73, puc: null, concepto: "O Pérdida líquida del ejercicio", tipo: "renglon_total" },
  { rgl: 74, puc: null, concepto: "Compensaciones (Art. 147 ET - pérdidas fiscales)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "Compensación de excesos de renta presuntiva (parte de R74)", tipo: "renglon_total" },
  { rgl: 75, puc: null, concepto: "Renta líquida (R72 - R74)", tipo: "renglon_total" },
  { rgl: 76, puc: null, concepto: "Renta presuntiva", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "MAX(R75, R76) — paso intermedio para R79", tipo: "renglon_total" },
  { rgl: 77, puc: null, concepto: "Rentas exentas", tipo: "renglon_total" },
  { rgl: 78, puc: null, concepto: "Rentas gravables", tipo: "renglon_total" },
  { rgl: 79, puc: null, concepto: "RENTA LÍQUIDA GRAVABLE (MAX(R75,R76) - R77 + R78)", tipo: "renglon_total" },
  { rgl: 80, puc: null, concepto: "Ingresos por ganancias ocasionales del país y del exterior", tipo: "renglon_total" },
  { rgl: 81, puc: null, concepto: "Costos por ganancias ocasionales", tipo: "renglon_total" },
  { rgl: 82, puc: null, concepto: "Ganancias ocasionales no gravadas y exentas", tipo: "renglon_total" },
  { rgl: 83, puc: null, concepto: "Ganancias ocasionales gravables", tipo: "renglon_total" },
  { rgl: 84, puc: null, concepto: "Impuesto sobre las rentas líquidas gravables (R79 × tarifa)", tipo: "renglon_total" },
  { rgl: 85, puc: null, concepto: "De dividendos y participaciones gravadas 2017-2018", tipo: "renglon_total" },
  { rgl: 86, puc: null, concepto: "De dividendos y participaciones gravadas 2019-2022 (art. 240)", tipo: "renglon_total" },
  { rgl: 87, puc: null, concepto: "De dividendos y participaciones gravadas 2019-2022 (27%)", tipo: "renglon_total" },
  { rgl: 88, puc: null, concepto: "De dividendos y participaciones gravadas 2023+ (art. 240)", tipo: "renglon_total" },
  { rgl: 89, puc: null, concepto: "De dividendos y participaciones gravadas 2023+ (32% o 33%)", tipo: "renglon_total" },
  { rgl: 90, puc: null, concepto: "De dividendos y participaciones recibidas de ECE", tipo: "renglon_total" },
  { rgl: 97, puc: null, concepto: "Impuesto de ganancias ocasionales (R83 × tarifa)", tipo: "renglon_total" },
  { rgl: 91, puc: null, concepto: "Total impuesto sobre las rentas líquidas gravables (R84 a R90)", tipo: "renglon_total" },
  { rgl: 93, puc: null, concepto: "Descuentos tributarios", tipo: "renglon_total" },
  { rgl: 94, puc: null, concepto: "Impuesto neto de renta (sin impuesto adicionado) = R91 - R93", tipo: "renglon_total" },
  { rgl: 96, puc: null, concepto: "Impuesto neto de renta (con impuesto adicionado) = R94 + R92 + R95", tipo: "renglon_total" },
  { rgl: 108, puc: null, concepto: "Anticipo renta para el año gravable siguiente", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(reservado para R92 VAA o R95 IA - agregar si aplica)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(obsoleto: usar R111 en f272)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(obsoleto: usar R112 en f273)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(obsoleto: usar R113 en f274)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(obsoleto: usar R114 en f275)", tipo: "renglon_total" },
  { rgl: 103, puc: null, concepto: "Anticipo renta liquidado año gravable anterior", tipo: "renglon_total" },
  { rgl: 104, puc: null, concepto: "Saldo a favor año gravable anterior sin solicitud de devolución", tipo: "renglon_total" },
  { rgl: 105, puc: null, concepto: "Autorretenciones", tipo: "renglon_total" },
  { rgl: 106, puc: null, concepto: "Otras retenciones", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "(espacio disponible)", tipo: "renglon_total" },
  { rgl: 107, puc: null, concepto: "Total retenciones año gravable a declarar (R105 + R106)", tipo: "renglon_total" },
  { rgl: 109, puc: null, concepto: "Anticipo Puntos adicionales año gravable anterior", tipo: "renglon_total" },
  { rgl: 100, puc: null, concepto: "Valor inversión obras por impuestos hasta del 50% de R99 (Modalidad 1)", tipo: "renglon_total" },
  { rgl: 101, puc: null, concepto: "Descuento efectivo inversión obras por impuestos (Modalidad 2)", tipo: "renglon_total" },
  { rgl: 111, puc: null, concepto: "Saldo a pagar por impuesto", tipo: "renglon_total" },
  { rgl: 112, puc: null, concepto: "Sanciones", tipo: "renglon_total" },
  { rgl: 113, puc: null, concepto: "Total saldo a pagar", tipo: "renglon_total" },
  { rgl: 114, puc: null, concepto: "Total saldo a favor", tipo: "renglon_total" },
  { rgl: 92, puc: null, concepto: "Valor a adicionar (VAA)", tipo: "renglon_total" },
  { rgl: 95, puc: null, concepto: "Impuesto a adicionar (IA)", tipo: "renglon_total" },
  { rgl: 98, puc: null, concepto: "Descuento por impuestos pagados en exterior por GO", tipo: "renglon_total" },
  { rgl: 99, puc: null, concepto: "Total impuesto a cargo (R96 + R97 - R98)", tipo: "renglon_total" },
  { rgl: 102, puc: null, concepto: "Crédito fiscal art. 256-1 E.T.", tipo: "renglon_total" },
  { rgl: 110, puc: null, concepto: "Anticipo Puntos adicionales año gravable siguiente", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "Concepto (suma a la Renta Líquida Ordinaria)", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "Inversiones liquidadas de períodos anteriores", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "Renta por recuperación de deducciones", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "Renta pasiva - ECE sin residencia fiscal Colombia", tipo: "renglon_total" },
  { rgl: null, puc: null, concepto: "TOTAL RENTAS ADICIONALES (suma a RLO)", tipo: "renglon_total" },
];

/** Cuentas detalle agrupadas por renglón. Útil para reportar */
/** la composición de cada renglón del F110 desde el balance.    */
export const CUENTAS_POR_RENGLON: ReadonlyMap<number, readonly string[]> =
  (() => {
    const m = new Map<number, string[]>();
    let renglonActual: number | null = null;
    for (const it of DETALLE_FISCAL_2516) {
      if (it.tipo === "renglon_total" && it.rgl !== null) {
        renglonActual = it.rgl;
        if (!m.has(renglonActual)) m.set(renglonActual, []);
      } else if (it.tipo === "cuenta" && it.puc && renglonActual !== null) {
        const arr = m.get(renglonActual) ?? [];
        arr.push(it.puc);
        m.set(renglonActual, arr);
      }
    }
    return m;
  })();
