// Catálogo oficial DIAN del Formato 2516 · generado desde modelo110.xlsm
// NO editar manualmente · regenerar con scripts/extract_f2516_h2h3.py

export type F2516_H2Renglon = {
  id: number;        // ID estable (fila Excel)
  nivel: number;      // 1=categoría principal, 2=sub, 3=sub-sub, ...
  concepto: string;
  esSumif: boolean;   // se alimenta del balance (captura)
  esTotal: boolean;   // suma de hijos (calculado)
};

export const F2516_H2_CATALOGO: F2516_H2Renglon[] = [
  { id: 10, nivel: 1, concepto: "ACTIVOS", esSumif: false, esTotal: false },
  { id: 11, nivel: 2, concepto: "Efectivo y equivalentes al efectivo", esSumif: false, esTotal: true },
  { id: 12, nivel: 3, concepto: "Efectivo", esSumif: true, esTotal: false },
  { id: 13, nivel: 3, concepto: "Equivalentes al efectivo", esSumif: true, esTotal: false },
  { id: 14, nivel: 3, concepto: "Efectivo restringido", esSumif: true, esTotal: false },
  { id: 15, nivel: 2, concepto: "Inversiones e instrumentos financieros derivados (valor neto)", esSumif: false, esTotal: false },
  { id: 16, nivel: 3, concepto: "Inversiones e instrumentos financieros derivados (valor bruto)", esSumif: false, esTotal: true },
  { id: 17, nivel: 4, concepto: "Derechos de recompra de inversiones", esSumif: true, esTotal: false },
  { id: 18, nivel: 4, concepto: "Inversiones en subsidiarias, asociadas y negocios conjuntos", esSumif: true, esTotal: false },
  { id: 19, nivel: 5, concepto: "Valor razonable con cambios en el ORI", esSumif: true, esTotal: false },
  { id: 20, nivel: 5, concepto: "Método de la participación", esSumif: true, esTotal: false },
  { id: 21, nivel: 5, concepto: "al costo", esSumif: true, esTotal: false },
  { id: 22, nivel: 4, concepto: "Instrumentos de deuda a costo amortizado", esSumif: true, esTotal: false },
  { id: 23, nivel: 4, concepto: "Instrumentos de deuda o patrimonio al costo", esSumif: true, esTotal: false },
  { id: 24, nivel: 4, concepto: "Instrumentos de deuda o patrimonio al valor razonable con cambios en resultados", esSumif: true, esTotal: false },
  { id: 25, nivel: 4, concepto: "Instrumentos de deuda o patrimonio al valor razonable con cambios en el ORI", esSumif: true, esTotal: false },
  { id: 26, nivel: 4, concepto: "Instrumentos financieros derivados con fines de negociación", esSumif: true, esTotal: false },
  { id: 27, nivel: 4, concepto: "Instrumentos financieros derivados con fines de cobertura", esSumif: true, esTotal: false },
  { id: 28, nivel: 4, concepto: "Derechos fiduciarios", esSumif: true, esTotal: false },
  { id: 29, nivel: 4, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 30, nivel: 3, concepto: "Deterioro acumulado de inversiones", esSumif: false, esTotal: true },
  { id: 31, nivel: 4, concepto: "Derechos de recompra de inversiones", esSumif: true, esTotal: false },
  { id: 32, nivel: 4, concepto: "Inversiones en subsidiarias, asociadas y negocios conjuntos", esSumif: true, esTotal: false },
  { id: 33, nivel: 5, concepto: "Costo", esSumif: true, esTotal: false },
  { id: 34, nivel: 4, concepto: "instrumentos de deuda a costo amortizado", esSumif: true, esTotal: false },
  { id: 35, nivel: 4, concepto: "Instrumentos de deuda o patrimonio al costo", esSumif: true, esTotal: false },
  { id: 36, nivel: 4, concepto: "Derechos fiduciarios", esSumif: true, esTotal: false },
  { id: 37, nivel: 4, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 38, nivel: 2, concepto: "Cuentas comerciales por cobrar y otras cuentas por cobrar", esSumif: false, esTotal: false },
  { id: 39, nivel: 3, concepto: "Cuentas y documentos por cobrar", esSumif: false, esTotal: true },
  { id: 40, nivel: 4, concepto: "Cartera de crédito (préstamos bancarios)", esSumif: true, esTotal: false },
  { id: 41, nivel: 4, concepto: "Cuentas comerciales por cobrar", esSumif: true, esTotal: false },
  { id: 42, nivel: 4, concepto: "Cuentas por cobrar en acuerdos de concesión (modelo del activo financiero)", esSumif: true, esTotal: false },
  { id: 43, nivel: 4, concepto: "Arrendamiento financiero o leasing financiero", esSumif: true, esTotal: false },
  { id: 44, nivel: 4, concepto: "Dividendos y participaciones", esSumif: true, esTotal: false },
  { id: 45, nivel: 4, concepto: "Cuentas por cobrar a socios, accionistas o partícipes", esSumif: true, esTotal: false },
  { id: 46, nivel: 4, concepto: "Cuentas y documentos por cobrar a otras partes relacionadas y asociadas", esSumif: true, esTotal: false },
  { id: 47, nivel: 4, concepto: "Primas de seguros por recaudar", esSumif: true, esTotal: false },
  { id: 48, nivel: 4, concepto: "Cartera de difícil cobro", esSumif: true, esTotal: false },
  { id: 49, nivel: 4, concepto: "Reclamaciones por cobrar", esSumif: true, esTotal: false },
  { id: 50, nivel: 4, concepto: "Anticipos de pagos", esSumif: true, esTotal: false },
  { id: 51, nivel: 4, concepto: "Otras cuentas y documentos por cobrar", esSumif: true, esTotal: false },
  { id: 52, nivel: 3, concepto: "Deterioro acumulado del valor cuentas y documentos por cobrar", esSumif: false, esTotal: true },
  { id: 53, nivel: 4, concepto: "Cartera de crédito (préstamos bancarios)", esSumif: true, esTotal: false },
  { id: 54, nivel: 4, concepto: "Cuentas comerciales por cobrar", esSumif: true, esTotal: false },
  { id: 55, nivel: 4, concepto: "Cuentas por cobrar en acuerdos de concesión (modelo del activo financiero)", esSumif: true, esTotal: false },
  { id: 56, nivel: 4, concepto: "Arrendamiento financiero o leasing financiero", esSumif: true, esTotal: false },
  { id: 57, nivel: 4, concepto: "Dividendos y participaciones", esSumif: true, esTotal: false },
  { id: 58, nivel: 4, concepto: "Cuentas por cobrar a socios, accionistas o partícipes", esSumif: true, esTotal: false },
  { id: 59, nivel: 4, concepto: "Cuentas por cobrar a otras partes relacionadas y asociadas", esSumif: true, esTotal: false },
  { id: 60, nivel: 4, concepto: "Otras cuentas por cobrar", esSumif: true, esTotal: false },
  { id: 61, nivel: 2, concepto: "Inventarios", esSumif: false, esTotal: true },
  { id: 62, nivel: 3, concepto: "Para la venta, no producidos por la empresa", esSumif: true, esTotal: false },
  { id: 63, nivel: 3, concepto: "En tránsito", esSumif: true, esTotal: false },
  { id: 64, nivel: 3, concepto: "Materias primas, suministros y materiales", esSumif: true, esTotal: false },
  { id: 65, nivel: 3, concepto: "En proceso (diferentes de obras o inmuebles en construcción para la venta)", esSumif: true, esTotal: false },
  { id: 66, nivel: 3, concepto: "Costos prestadores de servicios", esSumif: true, esTotal: false },
  { id: 67, nivel: 3, concepto: "Producto terminado (diferentes de obras o inmuebles terminados para la venta)", esSumif: true, esTotal: false },
  { id: 68, nivel: 3, concepto: "Obras o inmuebles en construcción para la venta", esSumif: true, esTotal: false },
  { id: 69, nivel: 3, concepto: "Obras o inmuebles terminados para la venta", esSumif: true, esTotal: false },
  { id: 70, nivel: 3, concepto: "Piezas de repuesto y equipo auxiliar clasificados como inventarios", esSumif: true, esTotal: false },
  { id: 71, nivel: 3, concepto: "Inventario que surge de la actividad de extracción", esSumif: true, esTotal: false },
  { id: 72, nivel: 3, concepto: "Deterioro acumulado del valor de inventarios", esSumif: true, esTotal: false },
  { id: 73, nivel: 2, concepto: "Gastos pagados por anticipado", esSumif: false, esTotal: true },
  { id: 74, nivel: 3, concepto: "Publicidad", esSumif: true, esTotal: false },
  { id: 75, nivel: 3, concepto: "Primas de seguros", esSumif: true, esTotal: false },
  { id: 76, nivel: 3, concepto: "Arrendamientos", esSumif: true, esTotal: false },
  { id: 77, nivel: 3, concepto: "Otros", esSumif: true, esTotal: false },
  { id: 78, nivel: 2, concepto: "Activos por impuestos corrientes", esSumif: false, esTotal: true },
  { id: 79, nivel: 3, concepto: "Saldos a favor por el impuesto de renta", esSumif: true, esTotal: false },
  { id: 80, nivel: 3, concepto: "Saldos a favor - otros impuestos y gravámenes", esSumif: true, esTotal: false },
  { id: 81, nivel: 3, concepto: "Descuentos tributarios", esSumif: true, esTotal: false },
  { id: 82, nivel: 3, concepto: "Anticipos y otros", esSumif: true, esTotal: false },
  { id: 83, nivel: 2, concepto: "Activos por impuestos diferidos", esSumif: true, esTotal: false },
  { id: 84, nivel: 2, concepto: "Propiedades, planta y equipo", esSumif: false, esTotal: true },
  { id: 85, nivel: 3, concepto: "Terrenos", esSumif: true, esTotal: false },
  { id: 86, nivel: 3, concepto: "Construcciones en proceso", esSumif: true, esTotal: false },
  { id: 87, nivel: 3, concepto: "Edificios", esSumif: true, esTotal: false },
  { id: 88, nivel: 5, concepto: "Ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 89, nivel: 3, concepto: "Activos tangibles para exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 90, nivel: 3, concepto: "Otras propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 91, nivel: 5, concepto: "Ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 92, nivel: 3, concepto: "Depreciación acumulada de propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 93, nivel: 3, concepto: "Deterioro acumulado de propiedades, planta y equipo", esSumif: true, esTotal: false },
  { id: 94, nivel: 2, concepto: "Activos intangibles", esSumif: false, esTotal: false },
  { id: 95, nivel: 3, concepto: "Activos intangibles distintos a la plusvalía", esSumif: false, esTotal: true },
  { id: 96, nivel: 4, concepto: "Acuerdos de concesión (modelo del activo intangible)", esSumif: true, esTotal: false },
  { id: 97, nivel: 4, concepto: "Activos intangibles exploración y evaluación de recursos minerales", esSumif: true, esTotal: false },
  { id: 98, nivel: 4, concepto: "Marcas, patentes, licencias y otros derechos", esSumif: true, esTotal: false },
  { id: 99, nivel: 5, concepto: "Ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 100, nivel: 4, concepto: "Arrendamiento Financiero", esSumif: true, esTotal: false },
  { id: 101, nivel: 5, concepto: "Ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 102, nivel: 4, concepto: "Otros activos intangibles", esSumif: true, esTotal: false },
  { id: 103, nivel: 5, concepto: "Ajuste acumulado por revaluaciones o reexpresiones", esSumif: true, esTotal: false },
  { id: 104, nivel: 4, concepto: "Amortización acumulada de activos intangibles distintos de la plusvalía", esSumif: true, esTotal: false },
  { id: 105, nivel: 4, concepto: "Deterioro acumulado de activos intangibles distintos de la plusvalía", esSumif: true, esTotal: false },
  { id: 106, nivel: 3, concepto: "Plusvalía o Good Will", esSumif: false, esTotal: true },
  { id: 107, nivel: 4, concepto: "Plusvalía o Good Will", esSumif: true, esTotal: false },
  { id: 108, nivel: 5, concepto: "Fusiones", esSumif: true, esTotal: false },
  { id: 109, nivel: 5, concepto: "Escisiones", esSumif: true, esTotal: false },
  { id: 110, nivel: 5, concepto: "Compra de acciones", esSumif: true, esTotal: false },
  { id: 111, nivel: 4, concepto: "Amortización acumulada de la plusvalía o Good Will", esSumif: true, esTotal: false },
  { id: 112, nivel: 4, concepto: "Deterioro acumulado de la plusvalía o Good Will", esSumif: true, esTotal: false },
  { id: 113, nivel: 2, concepto: "Propiedades de inversión", esSumif: false, esTotal: false },
  { id: 114, nivel: 3, concepto: "Terrenos y edificios", esSumif: true, esTotal: false },
  { id: 115, nivel: 5, concepto: "Al valor razonable", esSumif: true, esTotal: false },
  { id: 116, nivel: 3, concepto: "Depreciación acumulada de propiedades de inversión", esSumif: true, esTotal: false },
  { id: 117, nivel: 3, concepto: "Deterioro acumulado de propiedades de inversión", esSumif: true, esTotal: false },
  { id: 118, nivel: 2, concepto: "Activos no corrientes", esSumif: false, esTotal: false },
  { id: 119, nivel: 3, concepto: "Mantenidos para la venta", esSumif: true, esTotal: false },
  { id: 120, nivel: 3, concepto: "Deterioro acumulado activos no corrientes mantenidos para la venta", esSumif: true, esTotal: false },
  { id: 121, nivel: 3, concepto: "Mantenidos para distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 122, nivel: 3, concepto: "Deterioro acumulado activos no corrientes mantenidos para distribuir a los propietarios", esSumif: true, esTotal: false },
  { id: 123, nivel: 2, concepto: "Activos biológicos", esSumif: false, esTotal: false },
  { id: 124, nivel: 3, concepto: "Animales vivos", esSumif: false, esTotal: false },
  { id: 125, nivel: 4, concepto: "Animales productores medidos al costo", esSumif: true, esTotal: false },
  { id: 126, nivel: 4, concepto: "Depreciación acumulada de animales productores medidos al costo", esSumif: true, esTotal: false },
  { id: 127, nivel: 4, concepto: "Deterioro acumulado de animales productores medidos al costo", esSumif: true, esTotal: false },
  { id: 128, nivel: 4, concepto: "Animales productores medidos al valor razonable menos costos de venta", esSumif: true, esTotal: false },
  { id: 129, nivel: 4, concepto: "Animales consumibles medidos al costo", esSumif: true, esTotal: false },
  { id: 130, nivel: 4, concepto: "Deterioro acumulado animales consumibles medidos al costo", esSumif: true, esTotal: false },
  { id: 131, nivel: 4, concepto: "Animales consumibles medidos al valor razonable menos costos de venta", esSumif: true, esTotal: false },
  { id: 132, nivel: 3, concepto: "Plantas productoras y cultivos consumibles", esSumif: false, esTotal: false },
  { id: 133, nivel: 4, concepto: "Plantas productoras medidas al costo", esSumif: true, esTotal: false },
  { id: 134, nivel: 4, concepto: "Depreciación acumulada de plantas productoras", esSumif: true, esTotal: false },
  { id: 135, nivel: 4, concepto: "Deterioro acumulado de plantas productoras", esSumif: true, esTotal: false },
  { id: 136, nivel: 4, concepto: "Plantas productoras medidas al valor razonable", esSumif: true, esTotal: false },
  { id: 137, nivel: 4, concepto: "Cultivos consumibles medidos al costo", esSumif: true, esTotal: false },
  { id: 138, nivel: 4, concepto: "Deterioro acumulado cultivos consumibles medidos al costo", esSumif: true, esTotal: false },
  { id: 139, nivel: 4, concepto: "Cultivos consumibles medidos al valor razonable menos costos de venta", esSumif: true, esTotal: false },
  { id: 140, nivel: 2, concepto: "Otros activos", esSumif: false, esTotal: true },
  { id: 141, nivel: 3, concepto: "Activos plan de beneficios a empleados", esSumif: true, esTotal: false },
  { id: 142, nivel: 3, concepto: "Otros activos", esSumif: true, esTotal: false },
  { id: 143, nivel: 3, concepto: "Activos reconocidos solamente para fines fiscales", esSumif: true, esTotal: false },
  { id: 144, nivel: 2, concepto: "TOTAL ACTIVOS", esSumif: false, esTotal: false },
  { id: 145, nivel: 1, concepto: "PASIVOS", esSumif: false, esTotal: false },
  { id: 146, nivel: 2, concepto: "Obligaciones financieras y cuentas por pagar", esSumif: false, esTotal: true },
  { id: 147, nivel: 3, concepto: "Obligaciones financieras en moneda local", esSumif: true, esTotal: false },
  { id: 148, nivel: 3, concepto: "Obligaciones financieras en moneda extranjera", esSumif: true, esTotal: false },
  { id: 149, nivel: 3, concepto: "Depósitos y exigibilidades", esSumif: true, esTotal: false },
  { id: 150, nivel: 3, concepto: "Cuentas comerciales por pagar en moneda local", esSumif: true, esTotal: false },
  { id: 151, nivel: 3, concepto: "Cuentas comerciales por pagar en moneda extranjera", esSumif: true, esTotal: false },
  { id: 152, nivel: 3, concepto: "Dividendos y participaciones por pagar", esSumif: true, esTotal: false },
  { id: 153, nivel: 3, concepto: "Cuentas por pagar a socios, accionistas o partícipes", esSumif: true, esTotal: false },
  { id: 154, nivel: 3, concepto: "Cuentas y documentos por pagar a otras partes relacionadas y asociadas", esSumif: true, esTotal: false },
  { id: 155, nivel: 3, concepto: "Reserva matemática y/o técnica y otros pasivos exclusivos en compañías de seguros", esSumif: true, esTotal: false },
  { id: 156, nivel: 3, concepto: "Recaudo a favor de terceros", esSumif: true, esTotal: false },
  { id: 157, nivel: 3, concepto: "Otras cuentas y documentos por pagar en moneda local", esSumif: true, esTotal: false },
  { id: 158, nivel: 3, concepto: "Otras cuentas y documentos por pagar en moneda extranjera", esSumif: true, esTotal: false },
  { id: 159, nivel: 2, concepto: "Arrendamientos por pagar", esSumif: false, esTotal: true },
  { id: 160, nivel: 3, concepto: "Financiero o leasing - partes no relacionadas", esSumif: true, esTotal: false },
  { id: 161, nivel: 3, concepto: "Financiero o leasing - partes relacionadas", esSumif: true, esTotal: false },
  { id: 162, nivel: 3, concepto: "Operativo", esSumif: true, esTotal: false },
  { id: 163, nivel: 2, concepto: "Otros pasivos financieros", esSumif: false, esTotal: true },
  { id: 164, nivel: 3, concepto: "Bonos y documentos equivalentes", esSumif: true, esTotal: false },
  { id: 165, nivel: 3, concepto: "Instrumentos financieros derivados", esSumif: true, esTotal: false },
  { id: 166, nivel: 3, concepto: "Acciones preferenciales o aportes de capital clasificados como pasivos", esSumif: true, esTotal: false },
  { id: 167, nivel: 3, concepto: "Derechos fiduciarios", esSumif: true, esTotal: false },
  { id: 168, nivel: 3, concepto: "Otros pasivos financieros", esSumif: true, esTotal: false },
  { id: 169, nivel: 2, concepto: "Impuestos, gravámenes y tasas por pagar", esSumif: false, esTotal: true },
  { id: 170, nivel: 3, concepto: "Impuesto de renta", esSumif: true, esTotal: false },
  { id: 171, nivel: 3, concepto: "Impuesto al valor agregado - IVA", esSumif: true, esTotal: false },
  { id: 172, nivel: 3, concepto: "Otros impuestos, gravámenes y tasas por pagar", esSumif: true, esTotal: false },
  { id: 173, nivel: 2, concepto: "Pasivos por impuestos diferidos", esSumif: true, esTotal: false },
  { id: 174, nivel: 2, concepto: "Pasivos por beneficios a los empleados", esSumif: false, esTotal: true },
  { id: 175, nivel: 3, concepto: "De corto plazo", esSumif: true, esTotal: false },
  { id: 176, nivel: 3, concepto: "De largo plazo", esSumif: true, esTotal: false },
  { id: 177, nivel: 3, concepto: "Por terminación del vínculo laboral o contractual", esSumif: true, esTotal: false },
  { id: 178, nivel: 3, concepto: "Post empleo", esSumif: true, esTotal: false },
  { id: 179, nivel: 2, concepto: "Provisiones", esSumif: false, esTotal: true },
  { id: 180, nivel: 3, concepto: "Procesos legales (litigios y demandas)", esSumif: true, esTotal: false },
  { id: 181, nivel: 3, concepto: "Mantenimiento y reparaciones", esSumif: true, esTotal: false },
  { id: 182, nivel: 3, concepto: "Obligaciones fiscales", esSumif: true, esTotal: false },
  { id: 183, nivel: 3, concepto: "Desmantelamientos, restauración y rehabilitación", esSumif: true, esTotal: false },
  { id: 184, nivel: 3, concepto: "Garantías", esSumif: true, esTotal: false },
  { id: 185, nivel: 3, concepto: "Contratos onerosos", esSumif: true, esTotal: false },
  { id: 186, nivel: 3, concepto: "Reembolsos a clientes", esSumif: true, esTotal: false },
  { id: 187, nivel: 3, concepto: "Reestructuraciones de negocios", esSumif: true, esTotal: false },
  { id: 188, nivel: 3, concepto: "Pasivos contingentes asumidos en una combinación de negocios", esSumif: true, esTotal: false },
  { id: 189, nivel: 3, concepto: "Relacionadas con el medio ambiente", esSumif: true, esTotal: false },
  { id: 190, nivel: 3, concepto: "Otras provisiones", esSumif: true, esTotal: false },
  { id: 191, nivel: 2, concepto: "Pasivos por ingresos diferidos", esSumif: false, esTotal: true },
  { id: 192, nivel: 3, concepto: "Anticipos y avances recibidos de clientes", esSumif: true, esTotal: false },
  { id: 193, nivel: 3, concepto: "Ingresos diferidos por programas de fidelización", esSumif: true, esTotal: false },
  { id: 194, nivel: 3, concepto: "Subvenciones del gobierno y otras ayudas", esSumif: true, esTotal: false },
  { id: 195, nivel: 3, concepto: "Otros pasivos por ingresos diferidos", esSumif: true, esTotal: false },
  { id: 196, nivel: 2, concepto: "Otros pasivos", esSumif: false, esTotal: true },
  { id: 197, nivel: 3, concepto: "Depósitos recibidos", esSumif: true, esTotal: false },
  { id: 198, nivel: 3, concepto: "Retenciones a terceros sobre contratos", esSumif: true, esTotal: false },
  { id: 199, nivel: 3, concepto: "Embargos judiciales", esSumif: true, esTotal: false },
  { id: 200, nivel: 3, concepto: "Cuentas en participación", esSumif: true, esTotal: false },
  { id: 201, nivel: 3, concepto: "Pasivo para ejecución de excedentes - Régimen Tributario Especial", esSumif: true, esTotal: false },
  { id: 202, nivel: 3, concepto: "Fondos sociales, mutuales y otros", esSumif: true, esTotal: false },
  { id: 203, nivel: 3, concepto: "Otros pasivos", esSumif: true, esTotal: false },
  { id: 204, nivel: 3, concepto: "Pasivos reconocidos solamente para fines fiscales", esSumif: true, esTotal: false },
  { id: 205, nivel: 2, concepto: "TOTAL PASIVOS", esSumif: false, esTotal: false },
  { id: 206, nivel: 1, concepto: "PATRIMONIO (ACTIVOS - PASIVOS)", esSumif: false, esTotal: false },
  { id: 207, nivel: 1, concepto: "DETALLE PATRIMONIO CONTABLE", esSumif: false, esTotal: false },
  { id: 208, nivel: 2, concepto: "Capital social y reservas", esSumif: false, esTotal: true },
  { id: 209, nivel: 3, concepto: "Capital pagado", esSumif: true, esTotal: false },
  { id: 210, nivel: 3, concepto: "Acciones, cuotas o partes de interés social propias en cartera", esSumif: true, esTotal: false },
  { id: 211, nivel: 3, concepto: "Aportes sociales", esSumif: true, esTotal: false },
  { id: 212, nivel: 3, concepto: "Capital asignado", esSumif: true, esTotal: false },
  { id: 213, nivel: 3, concepto: "Fondo social mutual", esSumif: true, esTotal: false },
  { id: 214, nivel: 3, concepto: "Superávit de capital", esSumif: true, esTotal: false },
  { id: 215, nivel: 3, concepto: "Donaciones", esSumif: true, esTotal: false },
  { id: 216, nivel: 3, concepto: "Reservas legales o estatutarias", esSumif: true, esTotal: false },
  { id: 217, nivel: 3, concepto: "Reservas ocasionales", esSumif: true, esTotal: false },
  { id: 218, nivel: 3, concepto: "Reservas y fondos entidades solidarias", esSumif: true, esTotal: false },
  { id: 219, nivel: 3, concepto: "Asignaciones permanentes - Régimen Tributario Especial", esSumif: true, esTotal: false },
  { id: 220, nivel: 3, concepto: "Superávit por revaluaciones", esSumif: true, esTotal: false },
  { id: 221, nivel: 3, concepto: "Superávit método de participación", esSumif: true, esTotal: false },
  { id: 222, nivel: 3, concepto: "Dividendos o participaciones decretados en acciones, cuotas o partes de interés social", esSumif: true, esTotal: false },
  { id: 223, nivel: 3, concepto: "Saldo crédito Inversion suplementaria", esSumif: true, esTotal: false },
  { id: 224, nivel: 3, concepto: "Saldo débito Inversion suplementaria", esSumif: true, esTotal: false },
  { id: 225, nivel: 2, concepto: "Resultados del ejercicio", esSumif: false, esTotal: false },
  { id: 226, nivel: 3, concepto: "Utilidad o excedente del ejercicio en operaciones continuadas", esSumif: true, esTotal: false },
  { id: 227, nivel: 3, concepto: "Utilidad o excedente del ejercicio en operaciones discontinuadas", esSumif: true, esTotal: false },
  { id: 228, nivel: 3, concepto: "Pérdida o déficit del ejercicio en operaciones continuadas", esSumif: true, esTotal: false },
  { id: 229, nivel: 3, concepto: "Pérdida o déficit del ejercicio en operaciones discontinuadas", esSumif: true, esTotal: false },
  { id: 230, nivel: 2, concepto: "Resultados acumulados", esSumif: false, esTotal: false },
  { id: 231, nivel: 3, concepto: "Utilidades o excedentes acumulados susceptibles de distribución a título de no constitutivo de renta ni gananacia ocasional", esSumif: true, esTotal: false },
  { id: 232, nivel: 3, concepto: "Utilidades o excedentes acumulados susceptibles de distribución en calidad de gravados", esSumif: true, esTotal: false },
  { id: 233, nivel: 3, concepto: "Utilidades acumuladas por ajustes por correcciones de errores", esSumif: true, esTotal: false },
  { id: 234, nivel: 3, concepto: "Utilidades por ajustes por cambios en políticas contables", esSumif: true, esTotal: false },
  { id: 235, nivel: 3, concepto: "Pérdidas o déficit acumulados", esSumif: true, esTotal: false },
  { id: 236, nivel: 3, concepto: "Pérdidas acumuladas por ajustes por correcciones de errores", esSumif: true, esTotal: false },
  { id: 237, nivel: 3, concepto: "Pérdidas  por ajustes por cambios en políticas contables", esSumif: true, esTotal: false },
  { id: 238, nivel: 2, concepto: "Ganancias (pérdidas) acumuladas o retenidas por la adopción por primera", esSumif: false, esTotal: false },
  { id: 239, nivel: 3, concepto: "Ganancias acumuladas netas en la adopción por primera vez", esSumif: true, esTotal: false },
  { id: 240, nivel: 3, concepto: "Pérdidas acumuladas netas - adopción por primera vez", esSumif: true, esTotal: false },
  { id: 241, nivel: 2, concepto: "Otro resultado integral acumulado", esSumif: false, esTotal: false },
  { id: 242, nivel: 3, concepto: "Ajuste positivo por efecto de conversión", esSumif: true, esTotal: false },
  { id: 243, nivel: 3, concepto: "Ajuste negativo por efecto de conversión", esSumif: true, esTotal: false },
  { id: 244, nivel: 3, concepto: "Ganancias acumuladas - ORI", esSumif: true, esTotal: false },
  { id: 245, nivel: 3, concepto: "Pérdidas acumuladas - ORI", esSumif: true, esTotal: false },
  { id: 246, nivel: 2, concepto: "TOTAL PATRIMONIO CONTABLE", esSumif: false, esTotal: false },
  { id: 247, nivel: 1, concepto: "DATOS INFORMATIVOS", esSumif: false, esTotal: false },
  { id: 248, nivel: 2, concepto: "ACTIVOS", esSumif: true, esTotal: false },
  { id: 249, nivel: 4, concepto: "Total activos (fideicomitidos y generados) en el periodo gravable por fideicomisos o encargos fiduciarios en donde el contribuyente es fideicomitente o fiduciante", esSumif: true, esTotal: false },
  { id: 250, nivel: 4, concepto: "Inventarios de terceros", esSumif: true, esTotal: false },
  { id: 251, nivel: 4, concepto: "Inventarios en poder de terceros", esSumif: true, esTotal: false },
  { id: 252, nivel: 4, concepto: "Retención en la fuente trasladable (Art. 242-1 ET)", esSumif: true, esTotal: false },
  { id: 253, nivel: 2, concepto: "PASIVOS", esSumif: true, esTotal: false },
  { id: 254, nivel: 4, concepto: "Total pasivos (fideicomitidos y generados) en el periodo gravable por fideicomisos o encargos fiduciarios en donde el contribuyente es fideicomitente o fiduciante", esSumif: true, esTotal: false },
  { id: 255, nivel: 2, concepto: "PATRIMONIO", esSumif: true, esTotal: false },
  { id: 256, nivel: 4, concepto: "Dividendos o participaciones no gravados decretados en el periodo", esSumif: true, esTotal: false },
  { id: 257, nivel: 4, concepto: "Dividendos o participaciones gravados efectivamente pagados o exigibles en el periodo", esSumif: true, esTotal: false },
  { id: 258, nivel: 4, concepto: "Dividendos o participaciones no gravados efectivamente pagados o exigibles en el periodo", esSumif: true, esTotal: false },
  { id: 259, nivel: 4, concepto: "Dividendos o participaciones pagados o exigibles en el periodo, con cargo a utilidades del mismo período", esSumif: true, esTotal: false },
];
