// Generado automaticamente desde el .xlsm fuente.
// No editar a mano. Regenerar con scripts/build_form110_ts.py

export type Form110Section =
  | "Costos y deducciones"
  | "Datos informativos"
  | "Ganancias ocasionales"
  | "Ingresos"
  | "Liquidación privada"
  | "Patrimonio"
  | "Renta";

export type Form110Renglon = {
  numero: number;
  descripcion: string;
  seccion: Form110Section;
  formulaXlsm: string | null;  // referencia original (auditable)
  fuenteCelda: string | null;
};

export const FORM_110_2025: readonly Form110Renglon[] = [
  {
    numero: 5,
    descripcion: "Identificación Tributaria NIT",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D12",
    fuenteCelda: "B9",
  },
  {
    numero: 6,
    descripcion: "DV",
    seccion: "Datos informativos",
    formulaXlsm: "='Datos Informativos'!D13",
    fuenteCelda: "F9",
  },
  {
    numero: 7,
    descripcion: "Primer Apellido",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D14",
    fuenteCelda: "B12",
  },
  {
    numero: 8,
    descripcion: "Segundo Apellido",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D15",
    fuenteCelda: "F12",
  },
  {
    numero: 9,
    descripcion: "Primer Nombre",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D16",
    fuenteCelda: "B15",
  },
  {
    numero: 10,
    descripcion: "Otros Nombres",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D17",
    fuenteCelda: "F15",
  },
  {
    numero: 11,
    descripcion: "Razón Social",
    seccion: "Datos informativos",
    formulaXlsm: "='Datos Informativos'!D18",
    fuenteCelda: "B18",
  },
  {
    numero: 12,
    descripcion: "Cod. Dir. Seccional",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!C20",
    fuenteCelda: "F18",
  },
  {
    numero: 24,
    descripcion: "Actividad económica",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!C19",
    fuenteCelda: "B21",
  },
  {
    numero: 26,
    descripcion: "Nro. Formulario anterior",
    seccion: "Datos informativos",
    formulaXlsm: "29. Fracción año gravable siguiente",
    fuenteCelda: "B26",
  },
  {
    numero: 29,
    descripcion: "Fracción año gravable siguiente",
    seccion: "Datos informativos",
    formulaXlsm: "32. Pérdidas fiscales acumuladas años anteriores, sin compensar",
    fuenteCelda: "B29",
  },
  {
    numero: 30,
    descripcion: "renuncio a pertenecer al régimen tributario especial",
    seccion: "Datos informativos",
    formulaXlsm: null,
    fuenteCelda: null,
  },
  {
    numero: 31,
    descripcion: "Vinculado al pago de obras por impuestos",
    seccion: "Datos informativos",
    formulaXlsm: null,
    fuenteCelda: null,
  },
  {
    numero: 32,
    descripcion: "Pérdidas fiscales acumuladas años anteriores, sin compensar",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D57",
    fuenteCelda: "B30",
  },
  {
    numero: 33,
    descripcion: "Total costos y gastos de nómina",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D58",
    fuenteCelda: "D36",
  },
  {
    numero: 34,
    descripcion: "Aportes al sistema de seguridad social",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D59",
    fuenteCelda: "D39",
  },
  {
    numero: 35,
    descripcion: "Aportes al SENA, ICBF, cajas de compensación",
    seccion: "Datos informativos",
    formulaXlsm: "=+'Datos Informativos'!D60",
    fuenteCelda: "D42",
  },
  {
    numero: 36,
    descripcion: "Efectivo, bancos, otras inversiones",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H134",
    fuenteCelda: "D47",
  },
  {
    numero: 37,
    descripcion: "Inversiones e instrumentos financieros derivados",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H191",
    fuenteCelda: "D50",
  },
  {
    numero: 38,
    descripcion: "Cuentas, documentos y arrendamientos financieros por cobrar",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H315",
    fuenteCelda: "D53",
  },
  {
    numero: 39,
    descripcion: "Inventarios",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H386",
    fuenteCelda: "D56",
  },
  {
    numero: 40,
    descripcion: "Activos intangibles",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H461",
    fuenteCelda: "D59",
  },
  {
    numero: 41,
    descripcion: "Activos biológicos",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H519",
    fuenteCelda: "D62",
  },
  {
    numero: 42,
    descripcion: "Propiedades, planta y equipo, propiedades de inversión y ANCMV",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H933",
    fuenteCelda: "D65",
  },
  {
    numero: 43,
    descripcion: "Otros activos",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H1033",
    fuenteCelda: "D68",
  },
  {
    numero: 44,
    descripcion: "Total patrimonio bruto (sume 36 a 43)",
    seccion: "Patrimonio",
    formulaXlsm: "=SUM(D47:F68)",
    fuenteCelda: "D71",
  },
  {
    numero: 45,
    descripcion: "Pasivos",
    seccion: "Patrimonio",
    formulaXlsm: "='Hoja Sumaria'!H1500",
    fuenteCelda: "D74",
  },
  {
    numero: 46,
    descripcion: "Total patrimonio líquido (44-45)",
    seccion: "Patrimonio",
    formulaXlsm: "=IF(D71-D74>0,D71-D74,0)",
    fuenteCelda: "D77",
  },
  {
    numero: 47,
    descripcion: "Ingresos brutos de actividades ordinarias",
    seccion: "Ingresos",
    formulaXlsm: "=ROUND(SUMIFS('Hoja Sumaria'!H:H,'Hoja Sumaria'!C:C,$C82),-3)",
    fuenteCelda: "D82",
  },
  {
    numero: 48,
    descripcion: "Ingresos financieros",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1797",
    fuenteCelda: "D85",
  },
  {
    numero: 49,
    descripcion: "Dividendos y/o participaciones no constitutivos de renta ni ganancia ocasional (incluye capitalizaciones no gravadas)",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1800",
    fuenteCelda: "D88",
  },
  {
    numero: 50,
    descripcion: "Dividendos y/o participaciones distribuidos por entidades no residentes en Colombia a una CHC y prima en colocación de acciones",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1801",
    fuenteCelda: "D91",
  },
  {
    numero: 51,
    descripcion: "Dividendos y/o participaciones gravadas a la tarifa general provenientes de sociedades y entidades extranjeras o de sociedades nacionales",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1802",
    fuenteCelda: "D94",
  },
  {
    numero: 52,
    descripcion: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2016 y anteriores)",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1803",
    fuenteCelda: "D97",
  },
  {
    numero: 53,
    descripcion: "Dividendos y/o participaciones gravadas recibidas por personas naturales sin residencia fiscal (año 2017 y siguientes)",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1804",
    fuenteCelda: "D100",
  },
  {
    numero: 54,
    descripcion: "Dividendos y participaciones gravadas a las tarifas de los artículos 245 o 246 E.T.",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1805",
    fuenteCelda: "D103",
  },
  {
    numero: 55,
    descripcion: "Dividendos y/o participaciones gravadas a tarifa general (EP y sociedades extranjeras - utilidades generadas a partir del año 2017)",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1806",
    fuenteCelda: "D106",
  },
  {
    numero: 56,
    descripcion: "Dividendos y/o participaciones provenientes de proyectos calificados como megainversión gravadas al 27%",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H1807",
    fuenteCelda: "D109",
  },
  {
    numero: 57,
    descripcion: "Otros Ingresos",
    seccion: "Ingresos",
    formulaXlsm: "=ROUND(SUMIFS('Hoja Sumaria'!H:H,'Hoja Sumaria'!C:C,$C112),-3)",
    fuenteCelda: "D112",
  },
  {
    numero: 58,
    descripcion: "Total ingresos brutos (sume 47 a 57)",
    seccion: "Ingresos",
    formulaXlsm: "=SUM(D82:F112)",
    fuenteCelda: "D115",
  },
  {
    numero: 59,
    descripcion: "Devoluciones, rebajas y descuento en ventas",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H2027",
    fuenteCelda: "D118",
  },
  {
    numero: 60,
    descripcion: "Ingresos no constitutivos de renta ni ganancia ocasional",
    seccion: "Ingresos",
    formulaXlsm: "='Hoja Sumaria'!H2029",
    fuenteCelda: "D121",
  },
  {
    numero: 61,
    descripcion: "Total ingresos netos (58 - 59 - 60)",
    seccion: "Ingresos",
    formulaXlsm: "=IF(D115-D118-D121>0,D115-D118-D121,0)",
    fuenteCelda: "D124",
  },
  {
    numero: 62,
    descripcion: "Costos",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H2570",
    fuenteCelda: "D129",
  },
  {
    numero: 63,
    descripcion: "Gastos de administración",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H2831",
    fuenteCelda: "D132",
  },
  {
    numero: 64,
    descripcion: "Gastos y distribución de ventas",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H3104",
    fuenteCelda: "D135",
  },
  {
    numero: 65,
    descripcion: "Gastos financieros",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H3128",
    fuenteCelda: "D138",
  },
  {
    numero: 66,
    descripcion: "Otros gastos y deducciones",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H3231",
    fuenteCelda: "D141",
  },
  {
    numero: 67,
    descripcion: "Total costos y gastos deducibles (sume 62 a 66)",
    seccion: "Costos y deducciones",
    formulaXlsm: "=SUM(D129:F141)",
    fuenteCelda: "D144",
  },
  {
    numero: 68,
    descripcion: "Inversiones Efectuadas en el año",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H3234",
    fuenteCelda: "D151",
  },
  {
    numero: 69,
    descripcion: "Inversiones liquidadas en periodos gravables anteriores",
    seccion: "Costos y deducciones",
    formulaXlsm: "='Hoja Sumaria'!H3235",
    fuenteCelda: "D154",
  },
  {
    numero: 70,
    descripcion: "Renta por recuperación de deducciones",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3236",
    fuenteCelda: "D159",
  },
  {
    numero: 71,
    descripcion: "Renta liquida pasiva - Entidades controladoras del exterior sin residencia fiscal en Colombia",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3237",
    fuenteCelda: "D162",
  },
  {
    numero: 72,
    descripcion: "Renta liquida ordinaria del ejercicio (61+ 69 + 70 + 71 - 52 - 53 - 54 - 55 - 56 - 67 - 68)",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3247",
    fuenteCelda: "D165",
  },
  {
    numero: 73,
    descripcion: "Pérdida liquida ordinaria del ejercicio (52 + 53 + 54 + 55 + 56 + 67 + 68 - 61 - 69 - 70 - 71)",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3248",
    fuenteCelda: "D168",
  },
  {
    numero: 74,
    descripcion: "Compensaciones",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3249",
    fuenteCelda: "D171",
  },
  {
    numero: 75,
    descripcion: "Renta liquida (72 - 74)",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3250",
    fuenteCelda: "D174",
  },
  {
    numero: 76,
    descripcion: "Renta presuntiva",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3251",
    fuenteCelda: "D177",
  },
  {
    numero: 77,
    descripcion: "Rentas exenta",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3252",
    fuenteCelda: "D180",
  },
  {
    numero: 78,
    descripcion: "Rentas gravables",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3253",
    fuenteCelda: "D183",
  },
  {
    numero: 79,
    descripcion: "Renta liquida gravable (al mayor valor entre 75 y 76 reste 77 y sume 78)",
    seccion: "Renta",
    formulaXlsm: "='Hoja Sumaria'!H3261",
    fuenteCelda: "D186",
  },
  {
    numero: 80,
    descripcion: "Ingresos por ganancias ocasionales",
    seccion: "Ganancias ocasionales",
    formulaXlsm: "='Hoja Sumaria'!H3262",
    fuenteCelda: "D192",
  },
  {
    numero: 81,
    descripcion: "Costos por ganancias ocasionales",
    seccion: "Ganancias ocasionales",
    formulaXlsm: "='Hoja Sumaria'!H3265",
    fuenteCelda: "D195",
  },
  {
    numero: 82,
    descripcion: "Ganancias ocasionales no gravadas y exentas",
    seccion: "Ganancias ocasionales",
    formulaXlsm: "='Hoja Sumaria'!H3266",
    fuenteCelda: "D198",
  },
  {
    numero: 83,
    descripcion: "Ganancias ocasionales gravables",
    seccion: "Ganancias ocasionales",
    formulaXlsm: "='Hoja Sumaria'!H3267",
    fuenteCelda: "D201",
  },
  {
    numero: 84,
    descripcion: "Impuesto sobre la renta líquida gravable",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3269",
    fuenteCelda: "D206",
  },
  {
    numero: 85,
    descripcion: "Sobretasa (Puntos adicionales a la tarifa del impuesto renta)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3270",
    fuenteCelda: "D209",
  },
  {
    numero: 86,
    descripcion: "De dividendos y participaciones gravadas a la tarifa del 10% año 2022 y al 20% año 2023 y siguientes (base casilla 54):",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3271",
    fuenteCelda: "D212",
  },
  {
    numero: 88,
    descripcion: "De dividendos y/o participaciones gravadas a la tarifa del 27% (base casilla 56)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3273",
    fuenteCelda: "D218",
  },
  {
    numero: 89,
    descripcion: "De dividendos y/o participaciones gravadas a la tarifa del artículo 240 ET (base casilla 53)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3274",
    fuenteCelda: "D221",
  },
  {
    numero: 90,
    descripcion: "De dividendos y/o participaciones gravadas a la tarifa del 33% (base casilla 52)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3275",
    fuenteCelda: "D224",
  },
  {
    numero: 91,
    descripcion: "Total impuesto sobre las rentas liquidas gravables (84 + 85 + 86 + 87 + 88 + 89 + 90)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3276",
    fuenteCelda: "D227",
  },
  {
    numero: 92,
    descripcion: "Valor adicional (VAA)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3277",
    fuenteCelda: "D230",
  },
  {
    numero: 93,
    descripcion: "Descuentos tributarios",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3278",
    fuenteCelda: "D233",
  },
  {
    numero: 94,
    descripcion: "Impuesto neto de renta (sin impuesto adicionado) (91 + 92 - 93)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3279",
    fuenteCelda: "D236",
  },
  {
    numero: 95,
    descripcion: "Impuesto a adicionar (IA)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3280",
    fuenteCelda: "D239",
  },
  {
    numero: 96,
    descripcion: "Impuesto neto de renta (con impuesto adicionado) (94 + 95)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3281",
    fuenteCelda: "D242",
  },
  {
    numero: 97,
    descripcion: "Impuesto neto de ganancias ocasionales",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3282",
    fuenteCelda: "D245",
  },
  {
    numero: 98,
    descripcion: "Descuentos pagados en el exterior por ganancias ocasionales",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3283",
    fuenteCelda: "D248",
  },
  {
    numero: 99,
    descripcion: "Total impuesto a cargo (96 + 97 - 98)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3284",
    fuenteCelda: "D251",
  },
  {
    numero: 100,
    descripcion: "Valor inversión obras por impuestos hasta del 50% del valor de la casilla 88 (Modalidad de pago 1)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3285",
    fuenteCelda: "D254",
  },
  {
    numero: 101,
    descripcion: "Descuentos efectivo inversión obras por impuestos (modalidad de pago 2)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3286",
    fuenteCelda: "D257",
  },
  {
    numero: 102,
    descripcion: "Crédito fiscal (artículo 256-1 E.T.)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3287",
    fuenteCelda: "D260",
  },
  {
    numero: 103,
    descripcion: "Anticipo renta liquidado año gravable anterior",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3288",
    fuenteCelda: "D263",
  },
  {
    numero: 104,
    descripcion: "Saldo a favor año gravable anterior sin solicitud de devolución y/o compensación",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3289",
    fuenteCelda: "D266",
  },
  {
    numero: 105,
    descripcion: "Autorretenciones",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3290",
    fuenteCelda: "D270",
  },
  {
    numero: 106,
    descripcion: "Otras Retenciones",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3291",
    fuenteCelda: "D273",
  },
  {
    numero: 107,
    descripcion: "Total retenciones año gravable a declarar(105 + 106)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3292",
    fuenteCelda: "D276",
  },
  {
    numero: 108,
    descripcion: "Anticipo renta para el año gravable siguiente",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3293",
    fuenteCelda: "D279",
  },
  {
    numero: 109,
    descripcion: "Anticipo Puntos adicionales año gravable anterior",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3294",
    fuenteCelda: "D283",
  },
  {
    numero: 110,
    descripcion: "Anticipo Puntos adicionales año gravable siguiente",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3296",
    fuenteCelda: "D286",
  },
  {
    numero: 111,
    descripcion: "Saldo a pagar por impuesto (99 + 108 + 110 - 100 - 101 - 102 - 103 - 104 - 107 - 109)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3297",
    fuenteCelda: "D290",
  },
  {
    numero: 112,
    descripcion: "Sanciones",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3298",
    fuenteCelda: "D293",
  },
  {
    numero: 113,
    descripcion: "Total saldo a pagar (99 + 108 + 110 + 112 - 100 - 101 - 102 - 103 - 104 - 107-109)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3299",
    fuenteCelda: "D296",
  },
  {
    numero: 114,
    descripcion: "Total saldo a favor (100 + 101 + 102 + 103 + 104 + 107 + 109 - 99 - 108 - 110 - 112)",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3300",
    fuenteCelda: "D299",
  },
  {
    numero: 115,
    descripcion: "Valor impuesto exigible por obras por impuestos modalidad de pago 1",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3301",
    fuenteCelda: "D302",
  },
  {
    numero: 116,
    descripcion: "Valor total proyecto obras por impuestos modalidad de pago 2",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3302",
    fuenteCelda: "D305",
  },
  {
    numero: 117,
    descripcion: "Aporte voluntario Art. 244-1 E.T",
    seccion: "Liquidación privada",
    formulaXlsm: "='Hoja Sumaria'!H3303",
    fuenteCelda: "D308",
  },
  {
    numero: 994,
    descripcion: "Con salvedades",
    seccion: "Liquidación privada",
    formulaXlsm: null,
    fuenteCelda: null,
  },
] as const;
